"""Guide tiếng Việt biên soạn độc lập; decklist và thành tích nằm trong selected.json."""
PROFILES={}
def p(name, overview, first, second, tip, strength, weakness, starters, hand, steps, end, board, *, difficulty='intermediate', turn='going-first', tags=None):
    PROFILES[name]=dict(overview=overview,first=first,second=second,tip=tip,strength=strength,weakness=weakness,starters=starters,hand=hand,steps=steps,end=end,board=board,difficulty=difficulty,turn=turn,tags=tags or ['midrange','grind'])

p('Labrynth',
  'Control bằng Normal Trap; Arianna tìm engine, Big Welcome đổi quái trên sân và kích hoạt hiệu ứng khi quái rời sân bởi Trap.',
  'Ưu tiên Big Welcome và giữ đồ nội thất để chuẩn bị lượt sau; Lady tìm Trap theo tình huống.',
  'Daruma xử lý sân khó target; Arias giúp triển khai Trap nhanh hơn. Đừng dồn toàn bộ tài nguyên vào một Welcome.',
  'Lady phải chain trực tiếp sau Normal Trap để úp bài từ Deck; đối thủ có thể chen chain.',
  'Tái sử dụng Trap và kéo dài trận đấu tốt.', 'Ash chặn Welcome; banish GY làm đồ nội thất khó hồi phục.',
  ['Arianna the Labrynth Servant'],0,
  [('Normal Summon Arianna, tìm Big Welcome Labrynth.', ['Arianna the Labrynth Servant','Big Welcome Labrynth']),
   ('Úp Big Welcome, giữ Arianna trên sân đến lượt đối thủ.', ['Big Welcome Labrynth','Arianna the Labrynth Servant']),
   ('Big Welcome gọi Lovely từ Deck rồi trả Arianna về tay; xử lý trigger Lovely khi quái rời sân bởi Trap.', ['Big Welcome Labrynth','Lovely Labrynth of the Silver Castle','Arianna the Labrynth Servant'])],
  ['Lovely Labrynth of the Silver Castle'],'Lovely trên sân, Arianna về tay; Big Welcome trong GY cho vòng tương tác sau.',tags=['control','trap-heavy','grind'])
p('Mathmech',
  'Cyberse combo: Circular tạo tài nguyên cho Xyz, Superfactorial dùng ba Mathmech trong GY để dựng tương tác lượt đối thủ.',
  'Tìm Superfactorial và chuẩn bị Diameter trong GY; dùng engine @Ignister để mở rộng khi tay cho phép.',
  'Ép negate bằng các starter độc lập rồi lên Accesscode hoặc Terahertz; giữ tài nguyên GY khỏi Bystial.',
  'Circular hạn chế tấn công còn một quái; Sigma khóa Extra Deck vào Cyberse.',
  'Circular mở engine mà không cần Normal Summon.', 'Banish Sigma hoặc Diameter khiến Superfactorial mất hiệu lực.',
  ['Mathmech Circular'],0,
  [('Gửi Sigma từ Deck làm cost Circular, Special Summon Circular.', ['Mathmech Circular','Mathmech Sigma']),
   ('Hồi sinh Sigma khi không có quái ở Extra Monster Zone; Circular tìm Superfactorial.', ['Mathmech Sigma','Mathmech Circular','Mathmech Superfactorial']),
   ('Xyz Alembertian bằng hai Level 4, detach hai nguyên liệu để tìm Diameter; úp Superfactorial, chưa dùng được line ba quái nếu Diameter chưa vào GY.', ['Primathmech Alembertian','Mathmech Diameter','Mathmech Superfactorial'])],
  ['Primathmech Alembertian','Mathmech Superfactorial'],'Alembertian và Superfactorial úp, Diameter trên tay; cần nối engine để có đủ ba Mathmech trong GY.',difficulty='advanced',tags=['combo','cyberse'])
p('Salamangreat',
  'FIRE Cyberse xoay vòng Link tái triệu hồi, thu hồi tài nguyên và tạo negate bằng Roar.',
  'Lấy Sanctuary, tái Link Sunlight Wolf hoặc Raging Phoenix để có Roar và tài nguyên lượt sau.',
  'Dùng các lần triệu hồi nhỏ để ép tương tác trước khi lên Raging Phoenix; giữ Gazelle cho nhịp phục hồi.',
  'Gazelle cần một Salamangreat khác được gửi vào GY; không tự kích hoạt chỉ vì đối thủ gửi bài.',
  'Thu hồi quái và Trap qua nhiều lượt.', 'Negate Gazelle hoặc banish bài cần thu hồi làm giảm tài nguyên.',
  ['Salamangreat Gazelle'],0,
  [('Normal Summon Gazelle, gửi Roar từ Deck vào GY.', ['Salamangreat Gazelle','Salamangreat Roar']),
   ('Link Gazelle thành Balelynx, tìm Sanctuary.', ['Salamangreat Balelynx','Salamangreat Sanctuary']),
   ('Kích hoạt Sanctuary; dùng Balelynx làm nguyên liệu cho Balelynx thứ hai. Đây là mở đầu, chưa thu hồi được Roar.', ['Salamangreat Sanctuary','Salamangreat Balelynx'])],
  ['Salamangreat Balelynx','Salamangreat Sanctuary'],'Balelynx và Sanctuary; Roar trong GY, cần thêm extender để nối Sunlight Wolf/Raging Phoenix.',tags=['midrange','link','grind'])
p('White Forest',
  'White Forest đổi Spell/Trap lấy quái Tuner và search; build tham chiếu kết hợp Albaz/Cartesia để tận dụng Extra Deck và GY.',
  'Giữ Spell/Trap có khả năng tái úp để trả cost, dựng Synchro và Woes thay vì dùng cạn tay.',
  'Silvera đổi quái đối thủ về phòng thủ úp; nhánh Fusion bổ sung cách vượt sân.',
  'Spell/Trap White Forest được gửi để kích hoạt hiệu ứng quái có thể tự úp lại; lá tech thông thường không có khả năng này.',
  'Cost của engine có thể biến thành tài nguyên.', 'Droll và negate Tuner search cắt các nhánh combo.',
  ['Astellar of the White Forest','Tales of the White Forest'],0,
  [('Normal Summon Astellar; gửi Tales trên tay hoặc sân vào GY để gọi Silvy từ Deck.', ['Astellar of the White Forest','Tales of the White Forest','Silvy of the White Forest']),
   ('Silvy tìm Woes; Tales có thể úp lại nhờ đã được gửi để kích hoạt hiệu ứng quái.', ['Silvy of the White Forest','Woes of the White Forest','Tales of the White Forest']),
   ('Synchro Rciela bằng Astellar Level 2 và Silvy Tuner Level 4; úp Woes.', ['Rciela, Sinister Soul of the White Forest','Astellar of the White Forest','Silvy of the White Forest','Woes of the White Forest'])],
  ['Rciela, Sinister Soul of the White Forest','Woes of the White Forest'],'Rciela và Woes; Tales được tái úp. Rciela search cần thêm Spell/Trap để trả cost.')
p('White Forest Azamina',
  'Kết hợp Synchro White Forest với Fusion Azamina; các Sinful Spoils vừa trả cost vừa mở nhánh Fusion.',
  'Dựng Ilia Silvia và giữ Woes để chơi tiếp trong lượt đối thủ; hoàn thành các nhánh chưa bị khóa trước.',
  'Dùng Silvera cùng Fusion Azamina để xử lý quái; ép đối thủ tiêu negate vào search sớm.',
  'Đọc số Sinful Spoils cần gửi cho từng Fusion Azamina, không thay bằng Spell bất kỳ.',
  'Có tương tác từ cả Synchro lẫn Fusion.', 'Tay thiếu Spell/Trap trả cost dễ mất nhịp.',
  ['Astellar of the White Forest','Tales of the White Forest'],0,
  [('Normal Summon Astellar, gửi Tales để gọi Silvy từ Deck.', ['Astellar of the White Forest','Tales of the White Forest','Silvy of the White Forest']),
   ('Silvy tìm Woes; Tales tự úp lại khi trigger hợp lệ.', ['Silvy of the White Forest','Woes of the White Forest','Tales of the White Forest']),
   ('Synchro Rciela bằng Astellar và Silvy; úp Woes. Nhánh Azamina cần thêm Sinful Spoils, không tự có từ line này.', ['Rciela, Sinister Soul of the White Forest','Woes of the White Forest'])],
  ['Rciela, Sinister Soul of the White Forest','Woes of the White Forest'],'Mở đầu White Forest với Rciela và Woes; nối Azamina theo tài nguyên còn lại.',difficulty='advanced',tags=['combo','synchro','fusion'])
p('Centur-Ion',
  'Đặt quái Centur-Ion trong Spell/Trap Zone rồi gọi lại để Synchro trong lượt đối thủ; build này có nhánh Branded bổ trợ.',
  'Ưu tiên Primera, Trudea và Stand Up; dựng Auxila để giữ engine, dành Synchro tiếp cho lượt đối thủ.',
  'Dùng nhánh Albaz trước các khóa Extra Deck; chọn boss theo sân thay vì ép một line duy nhất.',
  'Trudea thay đổi Level thành 8 khi triệu hồi từ Spell/Trap Zone; kiểm tra vị trí ô trước khi đặt quái.',
  'Tái dựng engine qua nhiều lượt.', 'Phá Field Spell hoặc banish quái trong Spell/Trap Zone chặn Synchro.',
  ['Centur-Ion Trudea'],0,
  [('Normal Summon Trudea; đặt Trudea và Primera từ Deck vào Spell/Trap Zone.', ['Centur-Ion Trudea','Centur-Ion Primera']),
   ('Special Summon Primera từ Spell/Trap Zone, tìm Stand Up Centur-Ion! rồi kích hoạt Field Spell.', ['Centur-Ion Primera','Stand Up Centur-Ion!']),
   ('Gọi lại Trudea, tăng Level lên 8; Synchro Auxila bằng Trudea và Primera Level 4.', ['Centur-Ion Trudea','Centur-Ion Primera','Centur-Ion Auxila'])],
  ['Centur-Ion Auxila','Stand Up Centur-Ion!'],'Auxila và Stand Up; dùng search và End Phase của Auxila để chuẩn bị lượt sau.',tags=['synchro','midrange'])
p('Swordsoul',
  'Mo Ye và Taia tạo Tuner Token để Synchro; build đối chiếu thêm engine Albaz thay vì tập trung hoàn toàn vào Tenyi.',
  'Dựng Chixiao trước, giữ Longyuan và một Wyrm/Swordsoul làm cost để có Synchro Level 10.',
  'Baxia xử lý sân khi đúng nguyên liệu Wyrm; nhánh Branded cung cấp thêm đường Fusion.',
  'Khi điều khiển Swordsoul Token, Extra Deck chỉ được Synchro Summon.',
  'Line Chixiao ổn định và ít bước.', 'Negate Mo Ye trước khi tạo Token thường buộc cần extender.',
  ['Swordsoul of Mo Ye'],1,
  [('Normal Summon Mo Ye, reveal một Wyrm hoặc Swordsoul trên tay để gọi Token Level 4 Tuner.', ['Swordsoul of Mo Ye']),
   ('Synchro Chixiao bằng Mo Ye và Token; xử lý trigger Chixiao search và Mo Ye rút bài.', ['Swordsoul Grandmaster - Chixiao','Swordsoul of Mo Ye']),
   ('Tìm Longyuan bằng Chixiao; giữ một Wyrm/Swordsoul khác làm cost nếu muốn nối Level 10.', ['Swordsoul Grandmaster - Chixiao','Swordsoul Strategist Longyuan'])],
  ['Swordsoul Grandmaster - Chixiao'],'Chixiao, Longyuan trên tay và một lần rút; Level 10 chỉ có khi còn đúng cost.',tags=['synchro','midrange'])
p('Tenpai Dragon',
  'Deck đi sau dùng FIRE Dragon và Synchro trong Battle Phase để tạo sát thương liên tiếp.',
  'Nếu bị ép đi trước, giữ Kaimen và tài nguyên; Hieratic Seal là lựa chọn phòng thủ khi tay triển khai được.',
  'Dọn negate trước Battle Phase, ưu tiên Paidra tìm Kaimen hoặc Summoning rồi nối Chundra.',
  'Sangen Summoning bảo vệ FIRE Dragon ở Main Phase 1; không bảo vệ suốt Battle Phase.',
  'Có thể kết thúc trận trong một Battle Phase.', 'Bị chặn Battle Phase hoặc negate đúng Chundra làm mất khả năng kết liễu.',
  ['Tenpai Dragon Paidra'],0,
  [('Normal Summon Paidra, tìm Sangen Kaimen.', ['Tenpai Dragon Paidra','Sangen Kaimen']),
   ('Trong Battle Phase, dùng Kaimen tìm rồi Special Summon Chundra; chỉ thêm hiệu ứng triệu hồi khi kích hoạt trong Battle Phase.', ['Sangen Kaimen','Tenpai Dragon Chundra']),
   ('Cho Chundra chiến đấu; đầu Damage Step gọi Fadra từ Deck. Ngoài Damage Step, dùng Quick Effect Synchro Bident bằng Chundra và Paidra.', ['Tenpai Dragon Chundra','Tenpai Dragon Fadra','Tenpai Dragon Paidra','Sangenpai Bident Dragion'])],
  ['Sangenpai Bident Dragion','Tenpai Dragon Fadra'],'Bident và Fadra nếu đối thủ không ngắt line; kết quả sát thương phụ thuộc sân và các lần tấn công đã dùng.',turn='going-second',tags=['going-second','otk','synchro'])
p('Voiceless Voice',
  'Ritual midrange xoay quanh Lo, Barrier và Skull Guardian; build tham chiếu thêm Mitsurugi làm nhánh Ritual thứ hai.',
  'Giữ Lo cạnh Skull Guardian để có negate, dùng Barrier bảo vệ và duy trì search mỗi lượt.',
  'Ép tương tác bằng Mitsurugi trước khi dựng cặp Lo/Guardian; Sauravis bảo vệ các target quan trọng.',
  'Negate của Skull Guardian cần Lo trên sân hoặc trong GY; bảo vệ vị trí của Lo.',
  'End board gọn và vòng search bền.', 'Banish Lo hoặc phá Barrier trước khi ổn định engine làm giảm bảo vệ.',
  ['Lo, the Prayers of the Voiceless Voice','Saffira, Dragon Queen of the Voiceless Voice'],0,
  [('Normal Summon Lo, đặt Barrier từ Deck; Barrier tìm Skull Guardian.', ['Lo, the Prayers of the Voiceless Voice','Barrier of the Voiceless Voice','Skull Guardian, Protector of the Voiceless Voice']),
   ('Discard Saffira để gửi Prayers từ Deck vào GY và tìm một LIGHT Warrior/Dragon Ritual phù hợp.', ['Saffira, Dragon Queen of the Voiceless Voice','Prayers of the Voiceless Voice']),
   ('Banish Saffira từ GY để Ritual Summon Skull Guardian trên tay, dùng Lo làm toàn bộ Tribute; Lo hồi sinh khi LIGHT Ritual được gọi.', ['Saffira, Dragon Queen of the Voiceless Voice','Skull Guardian, Protector of the Voiceless Voice','Lo, the Prayers of the Voiceless Voice'])],
  ['Skull Guardian, Protector of the Voiceless Voice','Lo, the Prayers of the Voiceless Voice','Barrier of the Voiceless Voice'],'Lo, Skull Guardian và Barrier; một negate từ Guardian khi điều kiện được giữ.',tags=['ritual','midrange','grind'])
p('Yubel',
  'Yubel biến phá hủy quái của mình thành tài nguyên, dựng Phantom và nối Unchained để tương tác bằng Link.',
  'Lotus mở Spirit rồi tìm Nightmare Pain; giữ Yubel hợp lệ trong tay/GY để gọi Phantom.',
  'Super Polymerization đổi quái đối thủ thành Fusion; Nightmare Pain tạo áp lực sát thương khi đối thủ tấn công.',
  'Phantom dùng cách triệu hồi riêng bằng xào nguyên liệu; đây không phải Fusion Summon.',
  'Phá hủy có thể tạo thêm quái thay vì mất tài nguyên.', 'Banish hoặc trả quái về Deck tránh nhiều trigger bị phá hủy.',
  ['Samsara D Lotus'],0,
  [('Normal Summon Lotus, Tribute nó để gọi Spirit of Yubel từ Deck.', ['Samsara D Lotus','Spirit of Yubel']),
   ('Spirit tìm Nightmare Pain; kích hoạt Pain, phá Spirit rồi tìm một bài Yubel phù hợp.', ['Spirit of Yubel','Nightmare Pain']),
   ('Spirit bị phá gọi Yubel từ Deck; xào Yubel trên sân và Lotus trong GY để Special Summon Phantom.', ['Spirit of Yubel','Yubel','Samsara D Lotus','Phantom of Yubel'])],
  ['Phantom of Yubel','Nightmare Pain'],'Phantom và Nightmare Pain; Phantom đổi một hiệu ứng quái đối thủ thành phá Yubel khi có cost phù hợp.',tags=['combo','fiend','grind'])
p('Snake-Eye',
  'Snake-Eye dùng Level 1 FIRE để search và đặt quái thành Continuous Spell; mẫu MDM hiện tại có Yummy bổ trợ, khác trọng tâm guide Snake-Eye Yummy đã có.',
  'Mở Ash/Poplar để lấy Original Sinful Spoils, chuẩn bị Flamberge và Link tương tác.',
  'Dùng nhiều nhánh Level 1 để ép negate, chỉ chuyển sang vòng Link kết liễu sau khi xử lý backrow.',
  'Hiệu ứng thứ hai của Ash gửi chính nó và một bài face-up khác làm cost; quái đặt ở Spell/Trap Zone cũng có thể trả cost.',
  'Các quái nhỏ đổi thành tài nguyên trên nhiều vùng.', 'Ash bị negate hoặc GY bị banish làm yếu nhánh Link dài.',
  ['Snake-Eye Ash'],0,
  [('Normal Summon Ash, tìm Poplar; Poplar Special Summon từ tay vì được thêm vào tay ngoài việc rút.', ['Snake-Eye Ash','Snake-Eyes Poplar']),
   ('Poplar tìm Original Sinful Spoils - Snake-Eye.', ['Snake-Eyes Poplar','Original Sinful Spoils - Snake-Eye']),
   ('Ash gửi chính nó và Poplar để gọi Flamberge từ Deck; Poplar trong GY đặt một FIRE vào Spell/Trap Zone.', ['Snake-Eye Ash','Snake-Eyes Poplar','Snake-Eyes Flamberge Dragon'])],
  ['Snake-Eyes Flamberge Dragon'],'Flamberge và Original Sinful Spoils trên tay, kèm một FIRE đặt ở Spell/Trap Zone.',difficulty='advanced',tags=['combo','fire','link'])
p('Fire King',
  'Fire King phá quái của mình để tạo Garunix/Kirin và tài nguyên lượt sau; mẫu có Jurrac để thêm nhánh Dinosaur.',
  'Tìm Sanctuary/Island bằng Ponix, chuẩn bị Sacred Garunix cùng Kirin và Sky Burn.',
  'Dùng Kirin phá quái có trigger rồi buộc đối thủ tiêu tương tác trước Garunix Eternity.',
  'Phân biệt Fire King Avatar Kirin và Fire King High Avatar Kirin: hai lá khác hiệu ứng.',
  'Engine phục hồi mạnh sau phá hủy.', 'Banish thay vì destroy hoặc phá Island sai thời điểm khiến mất sân.',
  ['Legendary Fire King Ponix'],0,
  [('Normal Summon Ponix, tìm Fire King Sanctuary.', ['Legendary Fire King Ponix','Fire King Sanctuary']),
   ('Kích hoạt Sanctuary để đặt Fire King Island từ Deck.', ['Fire King Sanctuary','Fire King Island']),
   ('Island phá Ponix trên sân để tìm Sacred Fire King Garunix; Garunix Special Summon vì FIRE vừa bị phá.', ['Fire King Island','Legendary Fire King Ponix','Sacred Fire King Garunix'])],
  ['Sacred Fire King Garunix','Fire King Island','Fire King Sanctuary'],'Sacred Garunix và hai Spell engine; chọn quái FIRE trong Deck để Garunix phá theo tay hiện có.',tags=['midrange','fire','grind'])
p('Snake-Eye Fire King',
  'Snake-Eye cung cấp quái và Continuous Spell, Fire King dùng phá hủy để chuyển chúng thành tài nguyên.',
  'Triển khai nhánh Snake-Eye trước, dùng Original Sinful Spoils mở Ponix và giữ Kirin cho lượt đối thủ.',
  'Dùng Kirin/Garunix ép sân rồi tận dụng Link FIRE; không tự phá hết bài cần cho cost Ash.',
  'Original Sinful Spoils gửi một bài face-up làm cost và chỉ gọi Level 1 FIRE.',
  'Hai engine có thể nối qua Level 1 FIRE.', 'GY bị khóa và negate liên tiếp vào starter làm line dễ hụt.',
  ['Snake-Eye Ash'],0,
  [('Normal Summon Ash, tìm Poplar rồi Special Summon Poplar.', ['Snake-Eye Ash','Snake-Eyes Poplar']),
   ('Poplar tìm Original Sinful Spoils; dùng Spell này gửi Poplar trên sân để gọi Ponix từ Deck.', ['Snake-Eyes Poplar','Original Sinful Spoils - Snake-Eye','Legendary Fire King Ponix']),
   ('Ponix tìm Sanctuary; kích hoạt Sanctuary đặt Island. Ash vẫn trên sân để nối nhánh tiếp.', ['Legendary Fire King Ponix','Fire King Sanctuary','Fire King Island','Snake-Eye Ash'])],
  ['Snake-Eye Ash','Legendary Fire King Ponix','Fire King Island','Fire King Sanctuary'],'Ash, Ponix và Spell Fire King; line mở engine, chưa phải end board tối đa.',difficulty='advanced',tags=['combo','fire','grind'])
p('Rescue-ACE',
  'Turbulence úp nhiều Spell/Trap khác tên để tạo tương tác; Hydrant giúp search và dùng bài vừa úp.',
  'Giữ Hydrant và gọi Turbulence sau khi có hai Rescue-ACE trong GY; phân bổ CONTAIN/EXTINGUISH theo mục tiêu.',
  'Dùng board breaker trước Turbulence; EMERGENCY! tạo quái và trigger Tribute để nối engine.',
  'Turbulence cần banish hai Rescue-ACE từ GY để tự gọi; Hydrant chỉ cho kích hoạt một Quick-Play/Trap vừa úp mỗi lượt.',
  'Một Turbulence có thể đổi thành nhiều tương tác.', 'Negate Turbulence trước hiệu ứng úp bài làm mất payoff chính.',
  ['Rescue-ACE Air Lifter'],0,
  [('Normal Summon Air Lifter, tìm EMERGENCY!.', ['Rescue-ACE Air Lifter','EMERGENCY!']),
   ('EMERGENCY! gọi Hydrant từ Deck ở Defense rồi Tribute Air Lifter.', ['EMERGENCY!','Rescue-ACE Hydrant','Rescue-ACE Air Lifter']),
   ('Hydrant tìm Turbulence. Hiện chỉ có Air Lifter và EMERGENCY! trong GY, đủ banish để tự gọi Turbulence rồi úp bốn Rescue-ACE Spell/Trap khác tên.', ['Rescue-ACE Hydrant','Rescue-ACE Turbulence','CONTAIN!','EXTINGUISH!','RESCUE!','ALERT!'])],
  ['Rescue-ACE Hydrant','Rescue-ACE Turbulence','CONTAIN!','EXTINGUISH!','RESCUE!','ALERT!'],'Hydrant, Turbulence và bốn bài úp; dùng đúng điều kiện của từng Spell/Trap.',tags=['midrange','control'])
p('Melodious',
  'Pendulum/Fusion Fairy dùng Bacha kéo quái từ Deck, Etoile tạm banish Melodious để trả bài đối thủ về tay.',
  'Ostinato mở Bacha trên sân trống, triển khai Etoile và giữ nhánh hồi tài nguyên.',
  'Etoile xử lý nhiều bài bằng bounce; Schuberta cắt GY trước khi đối thủ hồi engine.',
  'Ostinato chỉ kích hoạt khi không điều khiển quái; xử lý Fusion bị phá và hồi nguyên liệu ở End Phase.',
  'Payoff Fusion mạnh từ starter ít lá.', 'Ash vào Ostinato hoặc negate Bacha chặn phần mở rộng.',
  ['Ostinato'],0,
  [('Khi sân không có quái, dùng Ostinato Fusion Bacha bằng Shopina và Soprano từ Deck.', ['Ostinato','Bacha the Melodious Maestra','Shopina the Melodious Maestra','Soprano the Melodious Songstress']),
   ('Bacha khi Fusion Summon gọi Refrain từ Deck.', ['Bacha the Melodious Maestra','Refrain the Melodious Songstress']),
   ('Refrain tìm Couplet trên tay để chuẩn bị Pendulum; chưa mặc định có Etoile từ ba bước này.', ['Refrain the Melodious Songstress','Couplet the Melodious Songstress'])],
  ['Bacha the Melodious Maestra','Refrain the Melodious Songstress'],'Bacha và Refrain, Couplet trên tay để nối engine.',tags=['fusion','pendulum','midrange'])
p('Purrely',
  'Các Memory trở thành Xyz Material, tăng hiệu ứng cho Epurrely rồi nâng thành Expurrely Noir nhiều nguyên liệu.',
  'Giữ My Friend và Street, tích đủ nguyên liệu cho Noir; Sleepy Memory giúp rút trong Standby Phase.',
  'Happiness tạo áp lực chiến đấu, Pretty Memory hỗ trợ xử lý sân; đừng đổi hết Memory thành triệu hồi nhỏ.',
  'Purrelyly dùng Memory trong GY để Xyz; Purrely dùng Memory trên tay được reveal.',
  'Xyz nhiều nguyên liệu và tài nguyên hồi từ My Friend.', 'Negate Purrelyly hoặc banish Memory mục tiêu chặn nâng Xyz.',
  ['Purrelyly','Purrely Delicious Memory'],1,
  [('Kích hoạt Delicious Memory với một mục tiêu hợp lệ trên sân; discard một lá và gọi Purrelyly từ Deck.', ['Purrely Delicious Memory','Purrelyly']),
   ('Purrelyly tìm My Friend Purrely; kích hoạt Continuous Spell nếu muốn mở thêm Memory.', ['Purrelyly','My Friend Purrely']),
   ('Purrelyly target Delicious Memory trong GY để Xyz Plump, gắn Memory làm nguyên liệu.', ['Purrelyly','Purrely Delicious Memory','Epurrely Plump'])],
  ['Epurrely Plump','My Friend Purrely'],'Plump với Purrelyly và Delicious làm nguyên liệu; cần tích thêm trước khi gọi Noir.',tags=['xyz','control','grind'])
p('Spright',
  'Quái Level/Rank/Link 2 tự gọi liên tiếp; Blue/Jet tìm engine, Gigantic và Elf tạo tài nguyên.',
  'Dựng Gigantic, Red/Carrot và Elf theo tay; dùng Gigantic sớm để giảm rủi ro Nibiru.',
  'Xyz Rank 2 ép tương tác, Smashers xử lý bài khó phá; Gamma Burst hỗ trợ sát thương.',
  'Sau hiệu ứng Gigantic, cả hai bên chỉ Special Summon Level/Rank/Link 2 trong phần còn lại của lượt.',
  'Nhiều extender không dùng Normal Summon.', 'Không có quái Level 2 mở sân khiến Blue/Jet khó hoạt động.',
  ['Nimble Beaver'],0,
  [('Normal Summon Beaver, gọi Beaver thứ hai từ Deck.', ['Nimble Beaver']),
   ('Xyz Gigantic bằng hai Beaver; detach một nguyên liệu để gọi Blue từ Deck.', ['Gigantic Spright','Spright Blue']),
   ('Blue tìm Jet; Special Summon Jet khi còn Level/Rank 2, rồi tìm Starter.', ['Spright Blue','Spright Jet','Spright Starter'])],
  ['Gigantic Spright','Spright Blue','Spright Jet'],'Gigantic, Blue và Jet, Starter trên tay; chỉ nối quái Level/Rank/Link 2 sau khóa.',tags=['combo','xyz','link'])
p('Runick',
  'Mẫu MDM là Runick Clown Crew: Runick cung cấp Quick-Play, Fountain hồi bài, Clown Crew tạo áp lực và Fusion.',
  'Dùng Hugin tìm Fountain, giữ Quick-Play tương tác và kết hợp Clown Crew thay vì chỉ dựa vào deck-out.',
  'Freezing Curses/Flashing Fire ép quái trước; nhớ các Quick-Play Runick làm bỏ Battle Phase kế tiếp.',
  'Mỗi Runick Quick-Play chọn một trong hai hiệu ứng; không vừa phá quái vừa gọi Hugin.',
  'Fountain đổi GY thành bài trên tay.', 'Phá hoặc banish Fountain khiến vòng rút yếu đi.',
  ['Runick Tip'],1,
  [('Dùng hiệu ứng triệu hồi của Runick Tip gọi Hugin vào Extra Monster Zone; không search bằng Tip trong cùng lần kích hoạt.', ['Runick Tip','Hugin the Runick Wings']),
   ('Hugin discard một lá để tìm Fountain; kích hoạt Fountain.', ['Hugin the Runick Wings','Runick Fountain']),
   ('Sau khi kích hoạt một Runick Quick-Play khác, dùng Fountain xào tối đa ba Quick-Play Runick từ GY để rút tương ứng.', ['Runick Fountain','Runick Freezing Curses'])],
  ['Hugin the Runick Wings','Runick Fountain'],'Hugin và Fountain; bước rút cần thêm một Quick-Play có điều kiện kích hoạt hợp lệ.',tags=['control','fusion','grind'])
p('Runick Spright',
  'Runick tạo Hugin Level 2 và vòng rút, Spright dùng Level 2 đó để triển khai Blue/Jet/Gigantic.',
  'Gọi Fusion Runick trước khi dùng khóa Gigantic; dựng Red/Carrot cùng Fountain.',
  'Dùng Quick-Play cắt sân rồi dựng Xyz/Link 2; không dựa vào OTK khi đã bỏ Battle Phase.',
  'Hugin Level 2 hợp với khóa Gigantic; Geri Level 4 không được gọi sau khóa.',
  'Hugin vừa tìm Fountain vừa mở điều kiện Spright.', 'Fountain bị loại bỏ và starter bị negate khiến tay dễ hụt.',
  ['Runick Tip','Spright Blue'],1,
  [('Dùng Tip gọi Hugin; Hugin discard một lá tìm Fountain.', ['Runick Tip','Hugin the Runick Wings','Runick Fountain']),
   ('Special Summon Blue vì có Hugin Level 2; Blue tìm Jet.', ['Hugin the Runick Wings','Spright Blue','Spright Jet']),
   ('Gọi Jet, tìm Starter; kích hoạt Fountain, giữ Hugin hoặc dùng hai Level 2 để Xyz Gigantic.', ['Spright Jet','Spright Starter','Runick Fountain','Gigantic Spright'])],
  ['Spright Blue','Spright Jet','Hugin the Runick Wings','Runick Fountain'],'Ba Level 2 và Fountain trước khi chọn Xyz/Link; Starter trên tay.',tags=['control','xyz','grind'])
p('Dragon Link',
  'Rokket, Chaos và Bystial chuyển tài nguyên Dragon thành Link/Synchro; decklist hiện có thêm các Rokket mới.',
  'Tìm Boot Sector, giữ một đường hồi Rokket và Bystial; quyết định boss dựa trên khóa DARK còn lại.',
  'Bystial cắt LIGHT/DARK trong GY rồi làm nguyên liệu; Borrelend tạo áp lực sau khi đối thủ tiêu negate.',
  'Rokket Tracer khóa Extra Deck chỉ DARK sau khi resolve; hoàn thành Link không DARK trước đó.',
  'Có nhiều đường nối qua tài nguyên Dragon.', 'Droll và banish GY làm combo dài thiếu nguyên liệu.',
  ['Quick Launch'],0,
  [('Quick Launch gọi Rokket Tracer từ Deck.', ['Quick Launch','Rokket Tracer']),
   ('Link Tracer thành Striker Dragon, tìm Boot Sector Launch.', ['Rokket Tracer','Striker Dragon','Boot Sector Launch']),
   ('Kích hoạt Boot Sector; lưu ý chỉ gọi Rokket từ tay hoặc từ GY theo điều kiện chênh lệch số quái, không tự hồi Tracer trên sân trống đối thủ.', ['Boot Sector Launch','Rokket Tracer'])],
  ['Striker Dragon','Boot Sector Launch'],'Striker và Boot Sector; cần thêm Rokket trên tay hoặc điều kiện hồi GY để nối combo.',difficulty='advanced',tags=['combo','dragon','link'])
p('Thunder Dragon',
  'Thunder Dragon tạo lợi thế khi discard/banish và dựng Colossus; build MDM kết hợp Bystial và Branded.',
  'Kích hoạt hiệu ứng Thunder trên tay rồi chuẩn bị Thunder trên sân để gọi Colossus; giữ banish làm tài nguyên.',
  'Bystial cắt GY, Titan xử lý sân khi có hiệu ứng Thunder phù hợp; nhánh Branded thêm Fusion.',
  'Colossus cần một hiệu ứng Thunder trên tay đã được kích hoạt trong lượt và Tribute một Thunder Effect Monster.',
  'Colossus hạn chế search, engine có vòng banish.', 'Banish Colossus hoặc board breaker không destroy vượt được bảo vệ.',
  ['Thunder Dragon','Batteryman Solar'],0,
  [('Discard Thunder Dragon để tìm bản Thunder Dragon khác.', ['Thunder Dragon']),
   ('Normal Summon Solar, gửi Dragonroar từ Deck vào GY.', ['Batteryman Solar','Thunder Dragonroar']),
   ('Tribute Solar để Special Summon Colossus bằng điều kiện triệu hồi riêng; không dùng Thunder Dragon Fusion ở line này.', ['Batteryman Solar','Thunder Dragon Colossus'])],
  ['Thunder Dragon Colossus'],'Colossus ngăn đối thủ thêm bài từ Main Deck ngoài việc rút.',tags=['fusion','midrange','grind'])
p('Dragonmaid',
  'Dragonmaid đổi hình dạng ở Battle Phase và thu hồi Spell/Trap; Bystial/Branded bổ sung tài nguyên Dragon.',
  'Tìm Changeover/Tidying, dựng Sheou khi có Dragon Level 5 trở lên; không cố Fusion khi tay thiếu đúng nguyên liệu.',
  'Hospitality và Bystial giúp dựng lại sân; Tidying bounce rồi tạo nhịp triệu hồi sau.',
  'Sheou cần một Dragonmaid và một Dragon Level 5 trở lên, khác nguyên liệu House.',
  'Tài nguyên Dragon có thể tái sử dụng.', 'Starter nhỏ bị negate và thiếu Dragon lớn khiến payoff chậm.',
  ['Parlor Dragonmaid'],0,
  [('Normal Summon Parlor, gửi Dragonmaid Tidying từ Deck vào GY.', ['Parlor Dragonmaid','Dragonmaid Tidying']),
   ('Link Parlor thành Striker Dragon; không có Boot Sector trong build nên không lấy search đó.', ['Parlor Dragonmaid','Striker Dragon']),
   ('Banish Tidying từ GY để hồi Parlor; hiệu ứng Parlor đã dùng trong lượt nên không gửi thêm lần nữa.', ['Dragonmaid Tidying','Parlor Dragonmaid'])],
  ['Striker Dragon','Parlor Dragonmaid'],'Hai Dragon trên sân để nối Link; Tidying sẽ trả Parlor về tay ở End Phase theo hiệu ứng.',tags=['midrange','dragon','grind'])
p('Dinomorphia',
  'Trap Fusion dùng LP làm tài nguyên; Rexterm hạn chế hiệu ứng quái đối thủ theo LP hiện tại của bạn.',
  'Therizia úp Frenzy, gọi Kentregina/Rexterm trong Main Phase đối thủ; giữ Counter Trap bảo vệ Fusion.',
  'Dùng Evenly trước khi dựng sân, tận dụng Rexterm để ép đối thủ phải có cách xử lý ngoài quái.',
  'Frenzy chỉ dùng trong Main Phase đối thủ; LP thấp cũng làm deck dễ thua burn.',
  'Rexterm áp chế nhiều sân quái.', 'Phá Trap trước khi Fusion hoặc damage không qua combat rất nguy hiểm.',
  ['Dinomorphia Therizia'],0,
  [('Normal Summon Therizia, úp Frenzy từ Deck.', ['Dinomorphia Therizia','Dinomorphia Frenzy']),
   ('Trong Main Phase đối thủ, Frenzy trả nửa LP và Fusion Kentregina bằng Diplos trong Deck cùng Stealthbergia trong Extra Deck.', ['Dinomorphia Frenzy','Dinomorphia Kentregina','Dinomorphia Diplos','Dinomorphia Stealthbergia']),
   ('Kentregina trả nửa LP, banish Frenzy để áp dụng hiệu ứng Fusion; dùng Therizia trong Deck và Kentregina trên sân để gọi Rexterm.', ['Dinomorphia Kentregina','Dinomorphia Frenzy','Dinomorphia Therizia','Dinomorphia Rexterm'])],
  ['Dinomorphia Rexterm'],'Rexterm cùng Therizia ban đầu; LP đã giảm hai lần trước các cost khác.',tags=['control','trap-heavy','fusion'])
p('Exosister',
  'Rank 4 anti-GY: Martha mở hai quái, Mikailis tìm tương tác, Magnifica đổi nguyên liệu thành các lần banish.',
  'Dựng Mikailis tìm Returnia, chỉ lên Magnifica khi còn đủ hai Xyz Exosister.',
  'Banish engine GY hoặc bài bảo vệ trước, dùng Returnia đúng điều kiện sân toàn Exosister.',
  'Martha khóa Special Summon vào Exosister trong lượt dùng hiệu ứng; đừng nối S:P sau đó.',
  'Tương tác banish phù hợp đối thủ dùng GY.', 'Negate Martha và không có extender Level 4 dễ dừng line.',
  ['Exosister Martha'],0,
  [('Khi sân trống hoặc chỉ có Xyz Exosister, Martha gọi chính nó và Elis từ Deck.', ['Exosister Martha','Exosister Elis']),
   ('Xyz Mikailis bằng hai Level 4.', ['Exosister Mikailis','Exosister Martha','Exosister Elis']),
   ('Detach một nguyên liệu của Mikailis tìm Returnia rồi úp Trap.', ['Exosister Mikailis','Exosister Returnia'])],
  ['Exosister Mikailis','Exosister Returnia'],'Mikailis và Returnia; Magnifica cần thêm một Xyz Exosister.',tags=['xyz','control','anti-graveyard'])
p('Floowandereeze',
  'Winged Beast dùng chuỗi Normal Summon thay vì Special Summon; Empen và Dreaming Town tạo áp lực trong lượt đối thủ.',
  'Robina lấy Eglen rồi tìm Empen; giữ Dreaming Town và Map để Tribute Summon lượt đối thủ.',
  'Raiza xử lý tài nguyên đối thủ, Unexplored Winds gửi bài làm Tribute theo điều kiện.',
  'Sau hiệu ứng quái nhỏ, bạn không Special Summon trong lượt đó; cần giữ chuỗi Normal Summon hợp lệ.',
  'Ít bị ảnh hưởng bởi hiệu ứng rút theo Special Summon.', 'Droll hoặc negate Robina trước search dễ làm đứt chuỗi.',
  ['Floowandereeze & Robina'],0,
  [('Normal Summon Robina, tìm Eglen rồi Normal Summon Eglen bằng hiệu ứng.', ['Floowandereeze & Robina','Floowandereeze & Eglen']),
   ('Eglen tìm Empen; Tribute Robina và Eglen để Normal Summon Empen bằng hiệu ứng Eglen.', ['Floowandereeze & Eglen','Floowandereeze & Empen','Floowandereeze & Robina']),
   ('Empen tìm Dreaming Town; xử lý các quái nhỏ bị banish để lấy lại tay, rồi úp Trap.', ['Floowandereeze & Empen','Floowandereeze and the Dreaming Town'])],
  ['Floowandereeze & Empen','Floowandereeze and the Dreaming Town'],'Empen, Dreaming Town và chim nhỏ hồi tay để chơi lượt sau.',tags=['control','normal-summon','grind'])
p('Traptrix',
  'Sera biến Normal Trap thành quái từ Deck và bài úp; mẫu MDM dùng thêm Zoodiac để có Xyz mà không tiêu Normal Summon.',
  'Dựng Sera và Holeutea, chọn Hole theo deck đối thủ; giữ nguyên liệu cho Rafflesia.',
  'Zoodiac mở đường Zeus, Traptrix tạo tài nguyên sau khi dùng Trap; Atypus tăng áp lực kết liễu.',
  'Holeutea discard một Normal Trap để dùng trong lượt vừa úp; cần chuẩn bị đúng loại bài.',
  'Sera có thể đổi một Trap thành nhiều tài nguyên.', 'Phá backrow trước khi engine chạy khiến sân Sera dễ bị vượt.',
  ['Traptrix Mantis'],0,
  [('Normal Summon Mantis, tìm Arachnocampa.', ['Traptrix Mantis','Traptrix Arachnocampa']),
   ('Link Mantis thành Sera; Special Summon Arachnocampa vì đang có Traptrix.', ['Traptrix Sera','Traptrix Arachnocampa']),
   ('Giữ Sera và Arachnocampa cùng các Trap có sẵn. Arachnocampa tự gọi không phải kích hoạt hiệu ứng trên sân, nên chưa tự kích Sera úp Holeutea.', ['Traptrix Sera','Traptrix Arachnocampa','Traptrix Holeutea'])],
  ['Traptrix Sera','Traptrix Arachnocampa'],'Sera và Arachnocampa; cần thêm Normal Trap để tạo giá trị từ Sera.',tags=['control','trap-heavy','xyz'])
p('Unchained',
  'Unchained phá bài của mình để gọi quái và dùng quái đối thủ làm Link Material; mẫu kết hợp Fiendsmith.',
  'Dựng Yama để tìm Sharvara, chuẩn bị Rage và Escape; làm nhánh không Fiend trước các khóa.',
  'Dùng Aruha/Sharvara phá bài có trigger, Rage/Anguish đổi quái đối thủ thành Link Material.',
  'Sharvara khóa Special Summon vào Fiend khi nó còn trên sân.',
  'Phá hủy có thể tạo tài nguyên và tương tác Link.', 'Banish thay vì phá khiến mất các trigger hồi quái.',
  ['Unchained Twins - Aruha','Escape of the Unchained'],0,
  [('Úp Escape; dùng Aruha trên tay phá Escape để Special Summon Aruha.', ['Unchained Twins - Aruha','Escape of the Unchained']),
   ('Escape bị phá gọi Sarama từ Deck.', ['Escape of the Unchained','Unchained Twins - Sarama']),
   ('Link Aruha và Sarama thành Yama; Yama tìm Sharvara.', ['Unchained Soul Lord of Yama','Unchained Twins - Aruha','Unchained Twins - Sarama','Unchained Soul of Sharvara'])],
  ['Unchained Soul Lord of Yama'],'Yama và Sharvara trên tay; cần thêm bài để phá khi nối Rage.',tags=['combo','fiend','link'])
p('Infernoble Knight',
  'Warrior FIRE dùng Equip Spell và Synchro Charles; decklist MDM kết hợp Flame Swordsman cùng K9.',
  'Tìm Equip phù hợp, hoàn thành các nhánh Link trước khi khóa triệu hồi của engine hỗ trợ.',
  'Dùng Flame Swordsman và Gearfried ép tương tác, chỉ nối Charles khi có đúng Tuner và tổng Level.',
  'Isolde tìm Warrior thì Warrior cùng tên không được triệu hồi hoặc kích hoạt hiệu ứng trong lượt đó.',
  'Equip tạo bảo vệ và tài nguyên kéo dài.', 'Negate Isolde hoặc mất Equip cost khiến nhánh Synchro chậm.',
  ['Infernoble Knight Ogier','Infernoble Knight Oliver'],1,
  [('Normal Summon Ogier, gửi Renaud từ Deck vào GY.', ['Infernoble Knight Ogier','Infernoble Knight - Renaud']),
   ('Oliver gửi một FIRE Warrior hoặc Equip Spell khác từ tay/sân vào GY để tự gọi thành Level 1 Tuner.', ['Infernoble Knight Oliver']),
   ('Synchro Angelica bằng Ogier Level 4 và Oliver Level 1; Angelica tìm Noble Arms Museum.', ['Angelica, Princess of Noble Arms','Infernoble Knight Ogier','Infernoble Knight Oliver','Noble Arms Museum'])],
  ['Angelica, Princess of Noble Arms'],'Angelica, Museum trên tay và Renaud trong GY; chưa tự có Charles.',difficulty='advanced',tags=['combo','warrior','synchro'])
p('Chimera',
  'Fusion Beast/Fiend/Illusion dùng Mirror Swordknight và Gazelle/Berfomet để tìm Chimera Fusion; mẫu thêm Fiendsmith và Hecahands.',
  'Giữ Chimera Fusion dùng lượt đối thủ và chuẩn bị GY Illusion; cân nhắc cost discard của Nightmare Apprentice.',
  'Guardian Chimera xử lý sân khi có đủ ba nguyên liệu và đúng số bài trên tay/sân.',
  'Big-Winged Berfomet khóa Extra Deck vào Fusion sau khi dùng hiệu ứng search.',
  'Fusion Material có thể mở search và tương tác GY.', 'Negate Berfomet hoặc banish Chimera Fusion làm mất vòng grind.',
  ['Mirror Swordknight'],0,
  [('Normal Summon Mirror Swordknight; Tribute nó để gọi Gazelle từ Deck.', ['Mirror Swordknight','Gazelle the King of Mythical Claws']),
   ('Gazelle tìm Big-Winged Berfomet; giữ Berfomet trên tay nếu không có cách Special Summon nó.', ['Gazelle the King of Mythical Claws','Big-Winged Berfomet']),
   ('Mirror Swordknight trong GY chỉ negate khi điều khiển Chimera the Flying Mythical Beast; cần Fusion phù hợp trước khi coi đây là tương tác.', ['Mirror Swordknight','Chimera the King of Phantom Beasts'])],
  ['Gazelle the King of Mythical Claws'],'Gazelle, Berfomet trên tay và Swordknight trong GY; cần extender/Fusion để dựng payoff.',tags=['fusion','midrange','grind'])
p('Ancient Gear',
  'EARTH Machine đi sau, dùng Fusion Giant và các nhánh Train để chuyển sân đã dọn thành sát thương lớn.',
  'Nếu đi trước, giữ tương tác từ tech; ưu tiên tài nguyên cho lượt sau thay vì tự dùng hết board breaker.',
  'Dọn negate trước Wyvern/Advance; Ballista đổi Geartown thành quái, Chaos Giant kết liễu khi đủ nguyên liệu.',
  'Wyvern cấm úp bài trong phần còn lại của lượt; úp bài cần thiết trước khi dùng search.',
  'Giant có sát thương và bảo vệ mạnh khi đã Fusion hợp lệ.', 'Search hoặc Fusion bị negate dễ hết tài nguyên sau khi dọn sân.',
  ['Ancient Gear Wyvern'],0,
  [('Normal Summon Wyvern, tìm Ancient Gear Advance.', ['Ancient Gear Wyvern','Ancient Gear Advance']),
   ('Kích hoạt Advance, tìm Ancient Gear Catapult.', ['Ancient Gear Advance','Ancient Gear Catapult']),
   ('Giữ Catapult: nó yêu cầu không điều khiển quái, nên không dùng ngay khi Wyvern còn trên sân. Cần giải phóng sân hoặc đi một nhánh khác.', ['Ancient Gear Catapult','Ancient Gear Wyvern'])],
  ['Ancient Gear Wyvern','Ancient Gear Advance'],'Wyvern và Advance, Catapult trên tay; đây là line chuẩn bị, không phải OTK một lá.',turn='going-second',tags=['going-second','otk','fusion'])
p('Memento',
  'Memento phá quái của mình để gom các tên khác nhau vào GY; Fusion hỗ trợ dựng Combined Creation và hồi engine.',
  'Lấy Shleepy/Fusion, lưu đủ năm tên cho Combined Creation; giữ Bone Party để né target và nối quái.',
  'Dùng Fusion cùng Super Polymerization xử lý sân; Combined Creation tạo áp lực lớn khi đã có đủ GY.',
  'Combined Creation cần xào năm Memento khác tên từ GY/tay; không thể thay bằng năm bản bất kỳ.',
  'Các quái nhỏ bị phá vẫn sinh tài nguyên.', 'Banish GY hoặc negate search Angwitch làm thiếu tên để gọi boss.',
  ['Mementotlan Angwitch'],0,
  [('Normal Summon Angwitch, tìm Shleepy.', ['Mementotlan Angwitch','Mementotlan Shleepy']),
   ('Shleepy reveal trên tay, phá Angwitch để tự gọi; Angwitch đã dùng search nên không dùng thêm hiệu ứng hồi cùng lượt.', ['Mementotlan Shleepy','Mementotlan Angwitch']),
   ('Shleepy gửi Goblin từ Deck vào GY để thực hiện Fusion bằng nó trên sân và Angwitch trong GY, gọi Twin Dragon.', ['Mementotlan Shleepy','Mementotlan Goblin','Mementotlan Angwitch','Mementotlan Twin Dragon'])],
  ['Mementotlan Twin Dragon'],'Twin Dragon, Goblin trong GY; tiếp tục hiệu ứng Fusion để mở rộng theo cost còn lại.',difficulty='advanced',tags=['combo','fusion','graveyard'])
p('P.U.N.K.',
  'Psychic trả LP để search và Synchro; build tham chiếu kết hợp Kashtira để tăng quái lớn và áp lực sân.',
  'Dựng Dragon Drive, chuẩn bị Sharakusai để Synchro trong lượt đối thủ và Trap của Madame Spider.',
  'Amazing Dragon bounce nhiều bài dựa vào các Level 3 Psychic khác tên trong GY.',
  'Foxy Tune gửi chính nó và một lá khác từ tay để gọi P.U.N.K.; LP thấp chưa tự đảm bảo End Punisher bất tử.',
  'Nhiều starter Psychic và search bằng Emergency Teleport.', 'Negate Ze Amin hoặc chặn GY làm các nhánh thiếu tài nguyên.',
  ['Noh-P.U.N.K. Ze Amin'],1,
  [('Normal Summon Ze Amin, trả 600 LP tìm Foxy Tune.', ['Noh-P.U.N.K. Ze Amin','Noh-P.U.N.K. Foxy Tune']),
   ('Foxy Tune gửi chính nó và một lá khác trên tay để gọi Deer Note từ Deck.', ['Noh-P.U.N.K. Foxy Tune','Noh-P.U.N.K. Deer Note']),
   ('Synchro Dragon Drive bằng Ze Amin Tuner Level 3 và Deer Note Level 5; resolve search Dragon Drive và hồi một P.U.N.K. khác Level 5 bằng Deer Note.', ['P.U.N.K. JAM Dragon Drive','Noh-P.U.N.K. Ze Amin','Noh-P.U.N.K. Deer Note'])],
  ['P.U.N.K. JAM Dragon Drive','Noh-P.U.N.K. Ze Amin'],'Dragon Drive và Ze Amin hồi sinh, kèm search Psychic Level 3 từ Dragon Drive.',tags=['synchro','combo'])
p('Goblin Biker',
  'Rank 3 dùng Xyz Material làm tài nguyên; Big Gabonga tìm Biker và hút quái khi có nguyên liệu bị detach.',
  'Dựng Gabonga, giữ một Biker có hiệu ứng detach và Full-Armored Xyz để chơi lượt đối thủ.',
  'Có thể detach nguyên liệu từ Xyz đối thủ theo hiệu ứng Biker; Dark Knight Lancer thêm đường xử lý quái.',
  'Gabonga hút quái cần sự kiện detach hợp lệ; không phải Quick Effect tự do bất kỳ lúc nào.',
  'Tận dụng được sân Xyz của cả hai bên.', 'Negate Gabonga làm Rank 3 thiếu search và tương tác.',
  ['Speedroid Terrortop'],0,
  [('Khi không điều khiển quái, Special Summon Terrortop và tìm Taketomborg.', ['Speedroid Terrortop','Speedroid Taketomborg']),
   ('Special Summon Taketomborg vì có WIND; Xyz Big Gabonga bằng hai Level 3, không dùng hiệu ứng Tribute Taketomborg.', ['Speedroid Taketomborg','Goblin Biker Big Gabonga']),
   ('Gabonga khi Xyz Summon tìm Dugg Charger để chuẩn bị hiệu ứng detach tiếp.', ['Goblin Biker Big Gabonga','Goblin Biker Dugg Charger'])],
  ['Goblin Biker Big Gabonga'],'Gabonga hai nguyên liệu và Dugg Charger trên tay; còn Normal Summon.',tags=['xyz','combo'])
p('Ryzeal',
  'Rank 4 Ryzeal kết hợp Time Thief/Zoodiac trong mẫu MDM; Duo Drive tìm tài nguyên, Detonator phá bài theo chain.',
  'Dựng Duo Drive để search rồi chuyển tài nguyên sang Detonator; giữ Cross/Plugin khi có trong build.',
  'Ép tương tác bằng các quái Level 4 độc lập, dùng Xyz toolbox theo sân.',
  'Các hiệu ứng triệu hồi Ryzeal thường khóa Extra Deck vào Rank 4 Xyz; kiểm tra từng lá trước khi dùng Zeus/TY-PHON.',
  'Rank 4 toolbox linh hoạt.', 'Negate Ice hoặc Duo Drive khiến thiếu quái và search tiếp.',
  ['Ice Ryzeal'],1,
  [('Normal Summon Ice, gọi Sword Ryzeal từ Deck.', ['Ice Ryzeal','Sword Ryzeal']),
   ('Sword khi được Special Summon tìm Ext Ryzeal.', ['Sword Ryzeal','Ext Ryzeal']),
   ('Xyz Duo Drive bằng Ice và Sword; có thể detach hai nguyên liệu để tìm hai Ryzeal khác tên nếu còn trả được cost.', ['Ryzeal Duo Drive','Ice Ryzeal','Sword Ryzeal'])],
  ['Ryzeal Duo Drive'],'Duo Drive và Ext trên tay; nhánh tìm thêm tùy số nguyên liệu còn lại và bài Ryzeal trong Deck.',tags=['xyz','midrange'])
p('Ice Barrier',
  'WATER Synchro tập trung Lancea; các quái Ice Barrier tạo body và áp lực điều kiện lên đối thủ.',
  'Dựng Lancea và chuẩn bị General Raiho trong Deck; dùng các nhánh Synchro trước khi bị khóa WATER.',
  'Trishula/Zero Dragon banish tài nguyên; Gymir hỗ trợ bảo vệ khi đủ Level.',
  'Revealer khóa Special Summon vào WATER sau khi resolve; Mirror Mage đổi Level qua hiệu ứng riêng.',
  'Lancea tạo tương tác khi đối thủ Special Summon.', 'Negate Revealer/Mirror Mage hoặc banish GY làm thiếu Tuner.',
  ['Revealer of the Ice Barrier'],1,
  [('Normal Summon Revealer, discard một lá để gọi Mirror Mage từ Deck.', ['Revealer of the Ice Barrier','Mirror Mage of the Ice Barrier']),
   ('Mirror Mage gọi tối đa ba Token Ice Barrier, mỗi Token Level 1; giảm Level Mirror Mage bằng số Token đã gọi.', ['Mirror Mage of the Ice Barrier']),
   ('Với ba Token, Mirror Mage còn Level 2 Tuner; dùng Revealer Level 4, Mirror Mage Level 2 và ba Token Level 1 để Synchro Trishula Level 9.', ['Revealer of the Ice Barrier','Mirror Mage of the Ice Barrier','Trishula, Dragon of the Ice Barrier'])],
  ['Trishula, Dragon of the Ice Barrier'],'Trishula; hiệu ứng banish chỉ có giá trị khi đối thủ có tài nguyên ở các vùng tương ứng.',tags=['synchro','water','midrange'])
p('Rikka',
  'Plant combo phối Rikka, Sunavalon và Aroma; Konkon cho phép Tribute quái đối thủ để trả cost Rikka.',
  'Chuẩn bị Konkon/Sheet và các nhánh Plant trước khi dùng khóa; giữ Princess trong GY hoặc tay để negate.',
  'Dùng Tribute để vượt bảo vệ destroy, Teardrop và Benghalancer xử lý các kiểu sân khác nhau.',
  'Rikka Petal khóa Special Summon vào Plant khi dùng hiệu ứng search/gửi; lên quái khác Type trước khóa.',
  'Có cách xử lý bằng Tribute và nhiều vòng hồi Plant.', 'Negate starter hoặc mất Field Spell khiến combo dài kém hiệu quả.',
  ['Rikka Petal'],0,
  [('Normal Summon Petal, tìm Mudan.', ['Rikka Petal','Mudan the Rikka Fairy']),
   ('Mudan Tribute Petal để tự gọi từ tay, rồi tìm Rikka Konkon.', ['Mudan the Rikka Fairy','Rikka Petal','Rikka Konkon']),
   ('Kích hoạt Konkon, úp Rikka Sheet từ Deck; giữ Mudan để đáp ứng điều kiện Sheet.', ['Rikka Konkon','Rikka Sheet','Mudan the Rikka Fairy'])],
  ['Mudan the Rikka Fairy','Rikka Konkon','Rikka Sheet'],'Mudan, Konkon và Sheet; Konkon có thể thay một Tribute Rikka bằng quái đối thủ khi điều kiện hợp lệ.',difficulty='advanced',tags=['combo','plant','control'])
p('Mikanko',
  'Đi sau bằng Equip và phản sát thương; Kaiju/Lava Golem dọn quái trước khi Mikanko chiến đấu.',
  'Giữ Hu-Li cùng Equip và tương tác; không tự đưa hết tài nguyên vào một quái nếu chưa có bảo vệ.',
  'Dọn negate rồi dùng Water Arabesque đổi quái thành Mikanko; Double-Edged Sword tăng sát thương khi đúng tình huống.',
  'Lava Golem làm mất Normal Summon/Set trong lượt; Water Arabesque có thể dùng trên quái đối thủ.',
  'Có thể thắng qua quái ATK lớn của đối thủ.', 'Bỏ Battle Phase hoặc gỡ Equip trước Damage Step làm mất phản sát thương.',
  ['Mikanko Water Arabesque'],0,
  [('Equip Water Arabesque vào một quái face-up đối thủ.', ['Mikanko Water Arabesque']),
   ('Dùng hiệu ứng Arabesque gọi Hu-Li từ Deck, chuyển Equip sang Hu-Li rồi trả quái cũ về tay.', ['Mikanko Water Arabesque','Hu-Li the Jewel Mikanko']),
   ('Hu-Li tìm một Mikanko Trap nếu Deck có; mẫu tham chiếu không có Trap Mikanko nên chỉ giữ body và Equip.', ['Hu-Li the Jewel Mikanko','Mikanko Water Arabesque'])],
  ['Hu-Li the Jewel Mikanko','Mikanko Water Arabesque'],'Hu-Li được Equip và một quái đối thủ bị bounce; còn cần sân/Equip để kết liễu.',turn='going-second',tags=['going-second','otk','equip'])
p('Vanquish Soul',
  'Midrange reveal thuộc tính trên tay để dùng hiệu ứng; Rock of the Vanquisher gọi và thu hồi quái mà không tạo cùng một line với K9.',
  'Razen tìm Mad Love, giữ FIRE/DARK/EARTH trên tay; Rock duy trì vòng quái trong lượt đối thủ.',
  'Đổi quái tránh target bằng Borger/Valius; reveal đúng thuộc tính trước khi cam kết phá sân.',
  'Reveal không discard; quái đã được reveal vẫn có thể làm điều kiện cho hiệu ứng tiếp theo.',
  'Nhiều Quick Effect linh hoạt và vòng hồi tay.', 'Tay thiếu tổ hợp thuộc tính khiến hiệu ứng mạnh không dùng được.',
  ['Vanquish Soul Razen'],0,
  [('Normal Summon Razen, tìm Mad Love.', ['Vanquish Soul Razen','Vanquish Soul Dr. Mad Love']),
   ('Link Razen thành Rock of the Vanquisher.', ['Vanquish Soul Razen','Rock of the Vanquisher']),
   ('Dùng Rock gọi Mad Love từ tay; Mad Love tìm Snow Devil.', ['Rock of the Vanquisher','Vanquish Soul Dr. Mad Love','Vanquish Soul Snow Devil'])],
  ['Rock of the Vanquisher','Vanquish Soul Dr. Mad Love','Vanquish Soul Snow Devil'],'Rock, Mad Love và Snow Devil úp; hiệu ứng Trap tùy thuộc tính còn trên tay.',tags=['midrange','control','grind'])
p('Radiant Typhoon',
  'WIND midrange dùng Quick-Play và Mystical Space Typhoon để kích hoạt các quái Radiant Typhoon; khác mẫu Zoodiac đã có.',
  'Giữ Quick-Play có mục tiêu hợp lệ, dựng quái engine và để dành chain tương tác lượt đối thủ.',
  'MST dọn Spell/Trap, Droplet/Crown xử lý quái; tránh dùng hết Quick-Play trước khi quái engine lên sân.',
  'MST phá hủy Spell/Trap, không negate hiệu ứng của lá đó.',
  'Quick-Play vừa tương tác vừa kích hoạt engine.', 'Thiếu Quick-Play hoặc bị chặn Special Summon làm quái engine kém hiệu quả.',
  ['Mystical Space Typhoon'],0,
  [('Giữ MST trong tay nếu đi sau, hoặc úp khi đi trước.', ['Mystical Space Typhoon']),
   ('Khi có mục tiêu Spell/Trap hợp lệ, kích hoạt MST; không dùng vào bài đã resolve nếu muốn ngăn hiệu ứng tức thời.', ['Mystical Space Typhoon']),
   ('Sau khi Quick-Play được kích hoạt, xử lý các trigger Radiant Typhoon đang có; từng lá có vùng kích hoạt và điều kiện riêng.', ['Radiant Typhoon Eldam','Radiant Typhoon Swen'])],
  [],'MST xử lý một Spell/Trap; quái Radiant Typhoon chỉ triển khai khi thật sự có trên tay/sân và thỏa điều kiện.',tags=['midrange','quick-play','wind'])
p('Crystron',
  'Machine Synchro dùng phá quái của mình và Tuner chơi lượt đối thủ; Inclusion/Sulfador mở tài nguyên mới.',
  'Chuẩn bị Tuner cùng non-Tuner đúng Level, giữ Cluster; tránh dùng non-Machine Synchro sau khóa engine.',
  'Quariongandrax banish nhiều quái khi đúng nguyên liệu; tech board breaker hỗ trợ trước Synchro.',
  'Các hiệu ứng gọi Tuner của Crystron có thể khóa Extra Deck vào Machine Synchro; đọc khóa trước khi nối Baronne.',
  'Có thể chuyển tài nguyên GY thành Synchro lượt đối thủ.', 'Banish Tuner hoặc negate hiệu ứng phá làm engine thiếu nguyên liệu.',
  ['Crystron Sulfefnir'],1,
  [('Discard một Crystron khác hoặc một lá bất kỳ hợp lệ theo Sulfefnir để tự gọi, rồi phá chính Sulfefnir.', ['Crystron Sulfefnir']),
   ('Sulfefnir bị phá gọi Smiger từ Deck ở Defense.', ['Crystron Sulfefnir','Crystron Smiger']),
   ('Smiger phá chính nó để gọi Citree Tuner từ Deck; chỉ nối Machine Synchro sau khóa. Smiger trong GY Level 3 với Citree Level 2 chuẩn bị Synchro Level 5 lượt sau.', ['Crystron Smiger','Crystron Citree'])],
  ['Crystron Citree'],'Citree trên sân và Smiger trong GY; cần một Machine Synchro Level 5 hợp lệ nếu muốn dùng cặp này.',difficulty='advanced',tags=['synchro','machine','control'])
p('Lightsworn',
  'Mill engine dùng Lightsworn, Fiendsmith và tài nguyên GY; mẫu đối chiếu có line burn, guide này tập trung mở GY.',
  'Tạo tài nguyên bằng Charge/Lumina, quản lý số lá còn trong Deck và các tên Lightsworn trước khi nối Extra Deck.',
  'Dùng tài nguyên đã mill để ép nhiều tương tác; không giả định luôn mill đúng Wulf/Felis.',
  'Wulf chỉ tự gọi khi được gửi từ Deck vào GY; discard từ tay không kích hoạt hiệu ứng đó.',
  'Mill đúng lá có thể mở nhiều nhánh miễn phí.', 'Kết quả phụ thuộc mill và rất nhạy với banish/khóa GY.',
  ['Charge of the Light Brigade'],0,
  [('Kích hoạt Charge, gửi ba lá trên cùng Deck vào GY làm cost và tìm Lumina.', ['Charge of the Light Brigade','Lumina, Lightsworn Summoner']),
   ('Nếu mill trúng Wulf, xử lý trigger gọi Wulf; nếu không thì không tự thêm body.', ['Wulf, Lightsworn Beast']),
   ('Normal Summon Lumina; hiệu ứng discard để hồi Lightsworn Level 4 trở xuống chỉ dùng nếu đã có mục tiêu hợp lệ trong GY.', ['Lumina, Lightsworn Summoner'])],
  ['Lumina, Lightsworn Summoner'],'Lumina và tài nguyên GY phụ thuộc ba lá mill; body bổ sung không được bảo đảm.',difficulty='advanced',tags=['combo','graveyard','mill'])
p('Infernoid',
  'Infernoid banish tài nguyên để tự gọi quái, dùng Tribute làm tương tác GY; các Spell mill mở nguồn nhiên liệu.',
  'Giữ Decatron và tài nguyên banish, dựng Flood hoặc boss theo tổng Level/Rank đang điều khiển.',
  'Onuncu/Devyaty dọn sân, các Infernoid nhỏ cắt GY; chọn thời điểm Tribute để không tự bỏ hết board.',
  'Triệu hồi riêng Infernoid kiểm tra tổng Level/Rank Effect Monster đang điều khiển; Link không có Level/Rank.',
  'Có thể phá sân và tiếp tục từ GY.', 'Mill không đúng bài hoặc bị Dimension Shifter khiến thiếu nhiên liệu.',
  ['Infernoid Decatron'],0,
  [('Normal Summon Decatron, gửi Onuncu từ Deck vào GY.', ['Infernoid Decatron','Infernoid Onuncu']),
   ('Decatron tăng Level theo Onuncu và sao chép tên/hiệu ứng; không được hiệu ứng dọn sân khi Onuncu tự Special Summon.', ['Infernoid Decatron','Infernoid Onuncu']),
   ('Giữ Decatron để Tribute một quái và negate Spell/Trap theo hiệu ứng đã sao chép; chỉ thêm Infernoid khi điều kiện tổng Level/Rank cho phép.', ['Infernoid Decatron'])],
  ['Infernoid Decatron'],'Decatron sao chép Onuncu; một tương tác Spell/Trap nếu có thể Tribute.',tags=['graveyard','control','mill'])
p('Supreme King',
  'Pendulum Supreme King phối Darkwurm/Gate Magician để search, tạo nguyên liệu cho Electrumite và các nhánh Z-ARC.',
  'Tạo hai scale trước khi tiêu Pendulum Summon; giữ Soul of the Supreme Celestial King cho payoff đúng điều kiện.',
  'Dùng Pendulum tạo nhiều body và chọn Synchro/Fusion theo sân; đừng gọi boss không đúng điều kiện material.',
  'Pendulum từ Extra Deck face-up cần Extra Monster Zone hoặc ô có Link chỉ xuống.',
  'Tái sử dụng Pendulum trong Extra Deck face-up.', 'Phá scale hoặc negate Electrumite làm thiếu nguyên liệu và search.',
  ['Supreme King Dragon Darkwurm'],0,
  [('Normal Summon Darkwurm, tìm Supreme King Gate Zero.', ['Supreme King Dragon Darkwurm','Supreme King Gate Zero']),
   ('Đặt Gate Zero vào Pendulum Zone làm scale thấp.', ['Supreme King Gate Zero']),
   ('Muốn Pendulum Summon cần thêm scale cao hợp lệ trên tay; Gate Zero và Darkwurm một mình không tự tạo cả hai scale.', ['Supreme King Gate Zero','Supreme King Gate Magician'])],
  ['Supreme King Dragon Darkwurm','Supreme King Gate Zero'],'Darkwurm và scale Gate Zero; cần một scale cao để tiếp tục.',difficulty='advanced',tags=['pendulum','combo'])
p('Endymion',
  'Pendulum Spellcaster tích Spell Counter để gọi quái và negate; Mythical Beast hỗ trợ tài nguyên cùng counter.',
  'Tích ba counter trên Servant trước khi gọi Endymion/Jackal King; giữ đủ counter cho các negate.',
  'Endymion từ Pendulum Zone có thể phá sân khi đủ counter; dùng Spell rút/search để ép tương tác trước.',
  'Đếm counter theo từng lá và từng hiệu ứng; không mặc định mọi Spell đều đặt counter lên mọi quái.',
  'Nhiều negate khi tài nguyên counter đầy đủ.', 'Tay thiếu Spell hoặc negate Servant đúng lúc làm combo hụt.',
  ['Servant of Endymion','Spell Power Mastery'],0,
  [('Đặt Servant vào Pendulum Zone.', ['Servant of Endymion']),
   ('Kích hoạt Spell Power Mastery tìm một Servant khác; sau resolve, Servant đã có counter từ Spell và có thể nhận thêm counter bằng Mastery theo số Mastery ở sân/GY.', ['Spell Power Mastery','Servant of Endymion']),
   ('Tiếp tục kích hoạt Spell hợp lệ cho đến khi Servant đủ ba counter; remove ba để gọi Servant và Endymion từ Deck, mỗi quái nhận một counter.', ['Servant of Endymion','Endymion, the Mighty Master of Magic'])],
  ['Servant of Endymion','Endymion, the Mighty Master of Magic'],'Servant và Endymion nếu đã có đủ ba counter; cần thêm Spell ngoài hai starter để hoàn tất.',difficulty='advanced',tags=['pendulum','spell-counter','combo'])
p('Dinos',
  'Dinosaur dùng phá Baby/Petiteranodon để gọi quái từ Deck; mẫu kết hợp GMX và Dinomorphia, khác guide GMX riêng.',
  'Dùng Miscellaneousaurus bảo vệ Main Phase, tạo đúng nhiên liệu cho Pill và chuẩn bị Tyranno/negate.',
  'Ultimate Conductor Tyranno úp quái rồi dọn sân qua chiến đấu; dùng hiệu ứng phá đúng Baby để mở thêm quái.',
  'Miscellaneousaurus chỉ bảo vệ Dinosaur trong Main Phase đó; không bảo vệ mọi vùng hoặc mọi giai đoạn.',
  'Destroy quái nhỏ có thể tạo chuỗi body.', 'Ash vào hiệu ứng gọi từ Deck hoặc mất Baby làm hụt nhánh.',
  ['Miscellaneousaurus','Babycerasaurus'],0,
  [('Discard Miscellaneousaurus; banish chính nó từ GY để gọi Archosaur Level 1.', ['Miscellaneousaurus','Animadorned Archosaur']),
   ('Archosaur phá Babycerasaurus trên tay, tìm Double Evolution Pill.', ['Animadorned Archosaur','Babycerasaurus','Double Evolution Pill']),
   ('Baby bị phá gọi Oviraptor từ Deck; Oviraptor tìm Ultimate Conductor Tyranno.', ['Babycerasaurus','Souleating Oviraptor','Ultimate Conductor Tyranno'])],
  ['Animadorned Archosaur','Souleating Oviraptor'],'Archosaur và Oviraptor, Pill/Tyranno trên tay; Pill còn cần banish một Dinosaur và một non-Dinosaur.',tags=['combo','dinosaur','otk'])
p('Gimmick Puppet',
  'Rank 8 Machine dùng Mansion và các Puppet mới; có line burn phức tạp nhưng guide này mở engine Xyz trước.',
  'Giữ Field Spell và các search để dựng Fantasix; quản lý khóa Gimmick Puppet trước khi chọn Extra Deck.',
  'Dùng Giant Grinder/Dark Strings theo sân; không coi combo burn là bảo đảm khi đối thủ có tương tác.',
  'Terror Baby hồi một Gimmick Puppet khác, không tự hồi chính nó.',
  'Rank 8 có thể tạo áp lực bằng destroy và damage.', 'Ash vào Field Spell hoặc negate Xyz search cắt chuỗi.',
  ['Mansion of the Dreadful Dolls'],0,
  [('Kích hoạt Mansion để tìm Rouge Doll.', ['Mansion of the Dreadful Dolls','Gimmick Puppet Rouge Doll']),
   ('Giữ Rouge Doll và dùng hiệu ứng tự gọi theo điều kiện hiện tại; một mình Mansion không được coi là đủ nguyên liệu cho mọi Xyz.', ['Gimmick Puppet Rouge Doll']),
   ('Khi có hai Level 8, Xyz Fantasix Machinix và dùng search Rank-Up-Magic; kiểm tra khóa Extra Deck trước khi tiếp tục.', ['Gimmick Puppet Fantasix Machinix','Rank-Up-Magic Argent Chaos Force'])],
  [],'Mansion và Rouge Doll trên tay; Fantasix cần thêm triển khai Level 8 hợp lệ.',difficulty='advanced',tags=['xyz','combo','burn'])
p('Phantom Knights',
  'GY Rank 3 dùng Torn Scales/Cloak/Boots để tìm quái và Fog Blade; mẫu thêm Mitsurugi và Radiant Typhoon.',
  'Chuẩn bị Rusty Bardiche và Fog Blade, giữ quái PK trong GY cho nhịp hồi sinh.',
  'Break Sword mở quái cấp cao hơn; Arc Rebellion hỗ trợ kết liễu khi vượt được khóa DARK.',
  'Sau hiệu ứng hồi của Break Sword, chỉ Special Summon DARK trong phần còn lại của lượt.',
  'GY cung cấp nhiều search và body.', 'Banish Cloak/Boots hoặc negate Torn Scales làm thiếu tài nguyên.',
  ['The Phantom Knights of Torn Scales'],1,
  [('Normal Summon Torn Scales, discard một lá để gửi Ancient Cloak từ Deck vào GY.', ['The Phantom Knights of Torn Scales','The Phantom Knights of Ancient Cloak']),
   ('Banish Cloak để tìm Silent Boots.', ['The Phantom Knights of Ancient Cloak','The Phantom Knights of Silent Boots']),
   ('Special Summon Boots vì có Phantom Knights; Xyz Break Sword bằng Boots và Torn Scales.', ['The Phantom Knights of Silent Boots','The Phantom Knights of Torn Scales','The Phantom Knights of Break Sword'])],
  ['The Phantom Knights of Break Sword'],'Break Sword; còn tài nguyên PK trong GY sau khi detach.',tags=['xyz','graveyard','combo'])
p('Raidraptor',
  'Winged Beast Rank-Up tạo Falcon Rank cao; mẫu MDM dùng thêm Mitsurugi/Magistus làm extender.',
  'Dựng Force Strix/Wise Strix, giữ Rank-Up cho boss; phải tính Rank và số nguyên liệu của từng nhánh.',
  'Các Falcon có bảo vệ mạnh sau khi được triệu hồi đúng; Glorious Bright hỗ trợ tương tác.',
  'Tribute Lanius gửi Mimicry là hiệu ứng có thể bị negate; Mimicry cần banish từ GY để search.',
  'Boss Rank cao có thể chịu được nhiều tương tác quái.', 'Negate Force Strix/Wise Strix làm hụt nhánh Rank-Up.',
  ['Raidraptor - Tribute Lanius'],0,
  [('Normal Summon Tribute Lanius, gửi Mimicry Lanius từ Deck vào GY.', ['Raidraptor - Tribute Lanius','Raidraptor - Mimicry Lanius']),
   ('Banish Mimicry để tìm Strangle Lanius.', ['Raidraptor - Mimicry Lanius','Raidraptor - Strangle Lanius']),
   ('Special Summon Strangle vì có DARK, Xyz Force Strix bằng hai Level 4; detach để search Singing Lanius.', ['Raidraptor - Strangle Lanius','Raidraptor - Force Strix','Raidraptor - Singing Lanius'])],
  ['Raidraptor - Force Strix'],'Force Strix và Singing Lanius trên tay để nối Winged Beast; còn khóa DARK.',difficulty='advanced',tags=['xyz','combo','rank-up'])
p('Blackwings',
  'Blackwing dùng các quái tự gọi và Tuner để Synchro; mẫu MDM kết hợp Allure Queen cùng nhánh Raidraptor.',
  'Mở Sudri/Vata, tính Level trước khi gửi từ Deck và giữ quái cho Synchro tiếp.',
  'Dùng Black-Winged Assault Dragon gây áp lực, nhánh Rank-Up cung cấp payoff khác khi tay phù hợp.',
  'Vata gọi Black-Winged Dragon bằng gửi nguyên liệu từ Deck; tổng Level phải đúng 8.',
  'Tuner được tìm từ starter và có nhiều nhánh Extra Deck.', 'Negate Sudri/Vata khiến thiếu Tuner hoặc body.',
  ['Blackwing - Sudri the Phantom Glimmer'],0,
  [('Normal Summon Sudri, tìm Vata.', ['Blackwing - Sudri the Phantom Glimmer','Blackwing - Vata the Emblem of Wandering']),
   ('Special Summon Vata vì có Blackwing khác trên sân.', ['Blackwing - Vata the Emblem of Wandering','Blackwing - Sudri the Phantom Glimmer']),
   ('Dùng Vata Level 2 cùng Zonda Level 6 từ Deck làm cost gửi để gọi Black-Winged Dragon Level 8.', ['Blackwing - Vata the Emblem of Wandering','Blackwing - Zonda the Dusk','Black-Winged Dragon'])],
  ['Blackwing - Sudri the Phantom Glimmer','Black-Winged Dragon'],'Sudri và Black-Winged Dragon; còn tài nguyên Zonda trong GY để nối lượt sau theo điều kiện.',difficulty='advanced',tags=['synchro','combo','winged-beast'])
p('Branded Predaplant',
  'Predaplant tìm Fusion Spell và tạo Predator Counter, Branded Fusion cung cấp nhánh Albaz trong cùng khung Fusion.',
  'Mở Ophrys/Cobra lấy Branded Fusion hoặc Instant Fusion; tôn trọng khóa Fusion của Branded Fusion cả lượt.',
  'Super Polymerization dùng quái đối thủ khi có đúng vật liệu; Counter hỗ trợ negate của Dragostapelia.',
  'Darlingtonia Cobra chỉ dùng search một lần mỗi Duel, không hồi lại search qua nhiều lượt.',
  'Nhiều đường tìm Fusion và xử lý quái đối thủ.', 'Negate Scorpio hoặc Ash vào Branded Fusion làm mất starter chính.',
  ['Predaplant Ophrys Scorpio'],1,
  [('Normal Summon Scorpio, gửi một quái từ tay vào GY để gọi Cobra từ Deck.', ['Predaplant Ophrys Scorpio','Predaplant Darlingtonia Cobra']),
   ('Cobra tìm Branded Fusion.', ['Predaplant Darlingtonia Cobra','Branded Fusion']),
   ('Dùng Branded Fusion gửi Fallen of Albaz và một DARK, ví dụ Byblisp từ Deck, để Fusion Lubellion; hiệu ứng Lubellion tiếp cần discard một lá.', ['Branded Fusion','Fallen of Albaz','Predaplant Byblisp','Lubellion the Searing Dragon'])],
  ['Predaplant Ophrys Scorpio','Predaplant Darlingtonia Cobra','Lubellion the Searing Dragon'],'Scorpio, Cobra và Lubellion; cần thêm discard để Lubellion tiếp tục Fusion.',tags=['fusion','midrange','control'])
p('Dogmatika',
  'Dogmatika dùng gửi Extra Deck vào GY để search/phá bài; mẫu MDM phối Mitsurugi và nhánh Albaz, không phải Ritual Dogmatika thuần.',
  'Hoàn thành nhánh Extra Deck cần dùng trước Nadir/Ecclesia; giữ Punishment đúng mục tiêu ATK.',
  'Nadir gửi N\'tss hoặc Garura để lấy hiệu ứng phụ; dùng Mitsurugi mở đường Ritual khi Extra Deck bị khóa.',
  'Dogmatika Punishment khóa Special Summon từ Extra Deck đến hết lượt kế tiếp của bạn.',
  'Extra Deck có giá trị ngay cả khi không triệu hồi.', 'Khóa tự áp dụng có thể chặn nhánh Albaz nếu dùng sai thứ tự.',
  ['Nadir Servant'],0,
  [('Nadir gửi Elder Entity N\'tss từ Extra Deck vào GY để tìm Ecclesia.', ['Nadir Servant',"Elder Entity N'tss",'Dogmatika Ecclesia, the Virtuous']),
   ('Nếu đối thủ có bài trên sân, xử lý trigger N\'tss để phá một bài.', ["Elder Entity N'tss"]),
   ('Normal Summon Ecclesia, tìm Punishment rồi úp; không triệu hồi từ Extra Deck sau khi Nadir resolve.', ['Dogmatika Ecclesia, the Virtuous','Dogmatika Punishment'])],
  ['Dogmatika Ecclesia, the Virtuous','Dogmatika Punishment'],'Ecclesia và Punishment; hiệu ứng N\'tss chỉ có khi có mục tiêu hợp lệ.',tags=['control','extra-deck-mill','ritual'])
p('SPYRAL',
  'SPYRAL dùng thông tin lá trên cùng Deck đối thủ và vòng GY của Master Plan/Quik-Fix; mẫu thêm Horus để tạo nguyên liệu.',
  'Drone xác định lá trên cùng trước khi đoán với Super Agent/Double Helix; giữ tài nguyên cho Sleeper.',
  'Dùng Sleeper phá bài và các body Horus để ép tương tác; đừng đoán ngẫu nhiên nếu có Drone.',
  'Quik-Fix tự hồi cần điều khiển Super Agent và discard; Double Helix được tính tên Super Agent trên sân/GY.',
  'Combo dài có nhiều nhánh search và hồi sinh.', 'Droll hoặc negate Master Plan làm mất nhiều tài nguyên.',
  ['SPYRAL GEAR - Drone','SPYRAL Super Agent'],0,
  [('Normal Summon Drone, xem và sắp thứ tự ba lá trên cùng Deck đối thủ.', ['SPYRAL GEAR - Drone']),
   ('Dùng Super Agent trên tay gọi đúng loại lá trên cùng để tự Special Summon.', ['SPYRAL Super Agent','SPYRAL GEAR - Drone']),
   ('Link Drone và Super Agent thành Double Helix; gọi đúng loại lá hiện tại để Special Summon Master Plan từ Deck vào ô Helix chỉ tới.', ['SPYRAL Double Helix','SPYRAL Master Plan'])],
  ['SPYRAL Double Helix','SPYRAL Master Plan'],'Double Helix và Master Plan nếu các lần đoán đúng; Master Plan tiếp tục search Mission.',difficulty='advanced',tags=['combo','link','graveyard'])
p('Speedroid',
  'WIND Synchro dùng Terrortop/Taketomborg và Tuner nhỏ; mẫu MDM thêm Radiant Typhoon để bổ sung body WIND.',
  'Tìm đúng Tuner và tính Level cho Hagoita/Clear Wing, hoàn thành nhánh không WIND trước khóa nếu có.',
  'Kitedrake dọn hoặc negate sân, Clear Wing tạo áp lực; tận dụng Quick-Play để mở Radiant Typhoon.',
  'Taketomborg Tribute để gọi Tuner sẽ khóa Special Summon vào WIND trong lượt đó.',
  'Terrortop mở engine mà không dùng Normal Summon.', 'Negate search hoặc không đủ tổng Level khiến Synchro bị kẹt.',
  ['Speedroid Terrortop'],0,
  [('Khi sân không có quái, Special Summon Terrortop, tìm Taketomborg.', ['Speedroid Terrortop','Speedroid Taketomborg']),
   ('Special Summon Taketomborg vì có WIND; Tribute nó để gọi CarTurbo Tuner từ Deck.', ['Speedroid Taketomborg','Speedroid CarTurbo']),
   ('Synchro Stardust Charge Warrior bằng Terrortop Level 3 và CarTurbo Level 3; Charge Warrior cho rút một lá khi Synchro Summon.', ['Speedroid Terrortop','Speedroid CarTurbo','Stardust Charge Warrior'])],
  ['Stardust Charge Warrior'],'Stardust Charge Warrior và một lần rút; còn Normal Summon, đã bị khóa WIND.',tags=['synchro','wind','combo'])
p('Gem-Knights',
  'Gem-Knight Fusion và các hỗ trợ mới tạo Fusion nối tiếp; Nepyrim/Quartz tìm tài nguyên, mẫu không mặc định là FTK.',
  'Giữ Gem-Knight Fusion trong GY để tái dùng và mở Dispersion; dựng Fusion theo nguyên liệu thật trên tay/sân.',
  'Dùng nhiều Fusion để ép negate; Amethyst/Prismaura xử lý bài theo hiệu ứng tương ứng.',
  'Nepyrim và hiệu ứng search Dispersion giảm nửa effect damage đối thủ nhận trong Main Phase của lượt đó.',
  'Fusion Spell có thể hồi từ GY.', 'Thiếu đúng nguyên liệu hoặc banish Fusion Spell làm combo chậm.',
  ['Gem-Knight Nepyrim','Gem-Armadillo'],0,
  [('Normal Summon Nepyrim, tìm Gem-Knight Fusion.', ['Gem-Knight Nepyrim','Gem-Knight Fusion']),
   ('Dùng hiệu ứng Nepyrim cho Normal Summon Gem-Armadillo; Armadillo tìm Quartz.', ['Gem-Knight Nepyrim','Gem-Armadillo','Gem-Knight Quartz']),
   ('Giữ Fusion và Quartz, chọn Fusion có nguyên liệu hợp lệ. Không dùng Nepyrim và Armadillo để gọi tùy ý một Fusion yêu cầu tên khác.', ['Gem-Knight Fusion','Gem-Knight Quartz'])],
  ['Gem-Knight Nepyrim','Gem-Armadillo'],'Nepyrim và Armadillo, Fusion/Quartz trên tay để nối theo điều kiện.',tags=['fusion','combo'])
p('Earth Machine',
  'EARTH Machine phối Crystron và Train mới để gom GY, hồi hai Machine và lên Rank 10.',
  'Gửi đúng Machine bằng Recycler, giữ Regulus hoặc Synchro tương tác; hồi Blue Traveler đúng thời điểm.',
  'Train Rank 10 tạo sát thương và Zeus khi hợp lệ; Crystron cung cấp nhánh Synchro hỗ trợ.',
  'Blue Traveler hồi chính nó và một EARTH Machine khác chỉ một lần mỗi Duel, rồi khóa Extra Deck vào Machine.',
  'GY có thể đổi thành hai body lớn.', 'Banish mục tiêu hồi hoặc negate Recycler làm thiếu nguyên liệu.',
  ['Scrap Recycler','Night Train Blue Traveler'],0,
  [('Discard Blue Traveler để tìm Revolving Switchyard.', ['Night Train Blue Traveler','Revolving Switchyard']),
   ('Normal Summon Recycler, gửi Heavy Freight Train Derricrane từ Deck vào GY.', ['Scrap Recycler','Heavy Freight Train Derricrane']),
   ('Blue Traveler trong GY target Derricrane, gọi cả hai; Xyz Gustav Max bằng hai Level 10.', ['Night Train Blue Traveler','Heavy Freight Train Derricrane','Superdreadnought Rail Cannon Gustav Max'])],
  ['Scrap Recycler','Superdreadnought Rail Cannon Gustav Max'],'Recycler và Gustav Max; detach Derricrane có thể kích hoạt hiệu ứng phá bài khi có mục tiêu.',tags=['xyz','machine','graveyard'])
p('Six Samurai',
  'Six Samurai dùng Warrior tự gọi và Tuner mới để Synchro; mẫu MDM thêm Primite/Mitsurugi, không dựa vào loop Gateway vô hạn.',
  'Tạo Synchro Shi En và giữ Spell/Trap bảo vệ; sử dụng Gateway theo lượng counter thật sự có.',
  'Dùng extender Warrior để ép tương tác trước boss, nhánh Mitsurugi thêm áp lực Ritual.',
  'Tactical Trainer và Anarchist Monk có giới hạn tự gọi mỗi lượt; không lặp vô hạn qua hồi tay.',
  'Nhiều quái tự Special Summon khi đã có Samurai.', 'Starter bị negate hoặc thiếu Tuner khiến Warrior không thành payoff.',
  ['Legendary Six Samurai - Kageki','Tactical Trainer of the Six Samurai'],0,
  [('Normal Summon Kageki, dùng hiệu ứng gọi Tactical Trainer Level 2 Tuner từ tay.', ['Legendary Six Samurai - Kageki','Tactical Trainer of the Six Samurai']),
   ('Synchro Legendary Lord Six Samurai - Shi En Level 5 bằng Kageki Level 3 và Tactical Trainer.', ['Legendary Six Samurai - Kageki','Tactical Trainer of the Six Samurai','Legendary Lord Six Samurai - Shi En']),
   ('Tactical Trainer được gửi từ sân vào GY tìm Six Strike - Double Assault.', ['Tactical Trainer of the Six Samurai','Six Strike - Double Assault'])],
  ['Legendary Lord Six Samurai - Shi En'],'Shi En và Double Assault trên tay; hiệu ứng bonus của Trainer giảm ATK quái đối thủ.',tags=['synchro','warrior','combo'])
p('Ritual Beasts',
  'Contact Fusion dùng Tamer và Spiritual Beast banish rồi tách Fusion để hồi tài nguyên; đòi hỏi quản lý tên đã Special Summon.',
  'Tạo Ulti-Cannahawk để search Steeds/Inheritance, sau đó giữ quái banish cho nhánh tách Fusion.',
  'Dùng Steeds phá quái và Link Reirautari khi đủ material; tránh mất các tên đã banish.',
  'Nhiều Ritual Beast chỉ được Special Summon một lần mỗi lượt theo tên; theo dõi từng tên, không chỉ từng bản.',
  'Banish là vùng tài nguyên, Contact Fusion không cần Spell.', 'Combo dễ sai giới hạn triệu hồi; negate Fusion search làm vòng tài nguyên yếu.',
  ['Ritual Beast Tamer Elder','Spiritual Beast Cannahawk'],0,
  [('Normal Summon Elder, dùng lượt Normal Summon bổ sung để gọi Cannahawk.', ['Ritual Beast Tamer Elder','Spiritual Beast Cannahawk']),
   ('Cannahawk banish Spiritual Beast Tamer Lara từ Deck.', ['Spiritual Beast Cannahawk','Spiritual Beast Tamer Lara']),
   ('Banish Elder và Cannahawk trên sân để Contact Fusion Ulti-Cannahawk; dùng search trả hai Ritual Beast banish về GY nếu muốn tìm Steeds.', ['Ritual Beast Tamer Elder','Spiritual Beast Cannahawk','Ritual Beast Ulti-Cannahawk','Ritual Beast Steeds'])],
  ['Ritual Beast Ulti-Cannahawk'],'Ulti-Cannahawk và Steeds nếu search resolve; chọn hai mục tiêu trả GY sao cho còn tài nguyên banish.',difficulty='advanced',tags=['combo','fusion','banish'])
p('Live☆Twin',
  'Live Twin tạo hai Level 2 từ một Normal Summon; Evil Twin hồi bạn đồng hành để rút/phá bài, Fiendsmith bổ sung engine.',
  'Làm nhánh Fiendsmith trước khóa Evil Twin nếu cần; giữ hai Link khác tên để rút và phá lượt đối thủ.',
  'Dùng Lil-la phá bài sau khi hồi, Trouble Sunny đổi sân thành tương tác và tài nguyên.',
  'Sau hiệu ứng hồi của Evil Twin, Extra Deck chỉ được gọi Fiend trong phần còn lại của lượt.',
  'Một starter mở hai body, vòng Link tạo lợi thế.', 'Negate quái Live Twin đầu tiên có thể chặn cả cặp.',
  ['Live☆Twin Ki-sikil'],0,
  [('Normal Summon Ki-sikil khi không có quái khác, gọi Lil-la từ Deck.', ['Live☆Twin Ki-sikil','Live☆Twin Lil-la']),
   ('Link hai quái thành Evil Twin Ki-sikil; dùng hiệu ứng hồi Lil-la.', ['Evil★Twin Ki-sikil','Live☆Twin Lil-la']),
   ('Link Ki-sikil và Lil-la thành Evil Twin Lil-la; hồi Evil Twin Ki-sikil để kích hoạt hiệu ứng rút của Ki-sikil.', ['Evil★Twin Lil-la','Evil★Twin Ki-sikil'])],
  ['Evil★Twin Ki-sikil','Evil★Twin Lil-la'],'Hai Evil Twin Link và một lần rút; đã bị khóa Fiend Extra Deck.',tags=['link','midrange','grind'])
p('Live☆Twin Spright',
  'Live Twin mở hai Level 2, Spright tạo search và tương tác; mẫu WCS trên MDM còn dùng Maliss/White Forest.',
  'Hoàn thành Gigantic/Elf trước khi dùng hiệu ứng hồi Evil Twin nếu muốn gọi non-Fiend.',
  'Spright tạo body thay thế khi Live Twin bị chặn; chọn Xyz/Link theo khóa đang áp dụng.',
  'Khóa Fiend của Evil Twin và khóa Level/Rank/Link 2 của Gigantic phải được xử lý đúng thứ tự.',
  'Live Twin và Spright chia sẻ điều kiện Level 2.', 'Nhiều engine làm tay có thể thiếu đúng cặp extender.',
  ['Live☆Twin Ki-sikil'],0,
  [('Normal Summon Ki-sikil, gọi Lil-la từ Deck khi không có quái khác.', ['Live☆Twin Ki-sikil','Live☆Twin Lil-la']),
   ('Xyz Gigantic bằng hai Level 2; detach để gọi Blue từ Deck.', ['Gigantic Spright','Spright Blue']),
   ('Blue tìm Jet; tự gọi Jet khi có Level/Rank 2 rồi tìm Starter. Chưa dùng hiệu ứng hồi Evil Twin ở line này.', ['Spright Blue','Spright Jet','Spright Starter'])],
  ['Gigantic Spright','Spright Blue','Spright Jet'],'Gigantic, Blue và Jet; chỉ nối Level/Rank/Link 2 sau Gigantic.',difficulty='advanced',tags=['combo','xyz','link'])
p('Naturia',
  'Mẫu Naturia Runick dùng Camellia/Mole Cricket tạo tài nguyên, Runick cung cấp Quick-Play và vòng rút.',
  'Camellia gửi Sacred Tree để lấy Blessing, giữ Sunflower cho negate quái và Fountain cho grind.',
  'Runick xử lý từng quái trước khi dựng Synchro; các lượt đã dùng Runick không có Battle Phase kế tiếp.',
  'Camellia có thể mill hai lá thay Tribute để trả cost Naturia, mỗi lượt theo giới hạn hiệu ứng.',
  'Cost negate có thể biến thành tài nguyên GY.', 'Banish Camellia hoặc phá Fountain khiến vòng engine yếu.',
  ['Naturia Mole Cricket'],0,
  [('Normal Summon Mole Cricket, Tribute để gọi Camellia từ Deck; gọi thêm quái chỉ khi đối thủ có quái ATK cao nhất theo điều kiện.', ['Naturia Mole Cricket','Naturia Camellia']),
   ('Camellia gửi Sacred Tree từ Deck vào GY; Sacred Tree tìm Naturia Blessing.', ['Naturia Camellia','Naturia Sacred Tree','Naturia Blessing']),
   ('Blessing hồi Mole Cricket từ GY; giữ cặp này để chuẩn bị Synchro hoặc hiệu ứng lượt đối thủ.', ['Naturia Blessing','Naturia Mole Cricket','Naturia Camellia'])],
  ['Naturia Camellia','Naturia Mole Cricket'],'Camellia và Mole Cricket; cần thêm đúng Level để lên Naturia Beast.',tags=['control','synchro','grind'])
p('Predaplant',
  'Predaplant dùng Fusion Spell và Predator Counter để xử lý quái; mẫu thuần engine khác nhánh Branded Predaplant.',
  'Tìm Instant Fusion/Spell hỗ trợ qua Cobra, dựng Fusion và giữ Predaplanning khi tay cho phép.',
  'Super Polymerization tận dụng quái đối thủ, Dragostapelia dùng Counter để negate.',
  'Cobra chỉ search một lần mỗi Duel; các khóa Fusion của Predaplant vẫn áp dụng sau khi rời sân nếu hiệu ứng đã resolve.',
  'Có nhiều cách tìm Fusion và tận dụng quái đối thủ.', 'Negate Scorpio/Cobra làm thiếu Fusion Spell.',
  ['Predaplant Ophrys Scorpio'],1,
  [('Normal Summon Scorpio, gửi một quái từ tay để gọi Cobra từ Deck.', ['Predaplant Ophrys Scorpio','Predaplant Darlingtonia Cobra']),
   ('Cobra tìm Instant Fusion; trả 1000 LP để gọi Ambulomelides.', ['Predaplant Darlingtonia Cobra','Instant Fusion','Predaplant Ambulomelides']),
   ('Ambulomelides tìm Predaplanning; úp Trap trước khi kết thúc lượt, Fusion gọi bởi Instant Fusion vẫn có hạn chế riêng.', ['Predaplant Ambulomelides','Predaplanning'])],
  ['Predaplant Ophrys Scorpio','Predaplant Darlingtonia Cobra','Predaplant Ambulomelides','Predaplanning'],'Scorpio, Cobra, Ambulomelides và Predaplanning trước End Phase; cần nối Fusion để giữ payoff lâu dài.',tags=['fusion','control'])
p('Primite',
  'Primite dùng Normal Monster làm tài nguyên; mẫu Bystial/Primite tận dụng Dragon thường để mở Synchro và tương tác.',
  'Ether Beryl úp Lordly Lode, gửi Normal Monster rồi giữ Drillbeam/Roar theo tay.',
  'Bystial tạo body và cắt GY, Primite cung cấp Normal Monster để mở các nhánh còn lại.',
  'Ether Beryl chỉ úp bài khi Normal Summon; Special Summon Beryl không kích hoạt hiệu ứng đó.',
  'Normal Monster có vai trò trong engine thay vì chỉ là brick.', 'Tay nhiều Normal Monster và thiếu Beryl/Spell làm chậm triển khai.',
  ['Primite Dragon Ether Beryl'],0,
  [('Normal Summon Ether Beryl, úp Primite Lordly Lode từ Deck.', ['Primite Dragon Ether Beryl','Primite Lordly Lode']),
   ('Kích hoạt Lordly Lode và xử lý search Primite theo hiệu ứng.', ['Primite Lordly Lode','Primite Roar']),
   ('Tribute Ether Beryl để gửi Labradorite Dragon từ Deck vào GY; chuẩn bị tài nguyên Normal Monster cho lượt sau.', ['Primite Dragon Ether Beryl','Labradorite Dragon'])],
  ['Primite Lordly Lode'],'Lordly Lode, một search Primite và Labradorite trong GY; Beryl có thể hồi tay ở Standby Phase khi điều kiện được giữ.',tags=['midrange','dragon','normal-monster'])
p('Ghoti',
  'Fish banish rồi quay lại, Synchro trong lượt đối thủ để dựng Askaan/Deep Beyond và xử lý sân bằng banish.',
  'Banish Tuner Ghoti có khả năng quay lại, giữ non-Tuner đúng Level; chọn thời điểm Synchro theo việc đối thủ dựng sân.',
  'White Aura Whale dọn quái Attack, Deep Beyond banish toàn sân khi được Synchro trong lượt đối thủ.',
  'Tuner Ghoti có điều kiện quay lại Standby Phase kế tiếp và Synchro riêng; banish không đồng nghĩa hồi ngay.',
  'Tài nguyên có thể quay lại từ banishment.', 'Banish sai thời điểm hoặc thiếu non-Tuner khiến không Synchro được.',
  ['Lifeless Leaffish','Gold Sarcophagus'],0,
  [('Normal Summon Leaffish, gửi một Fish như Snopios từ Deck vào GY.', ['Lifeless Leaffish','Snopios, Shade of the Ghoti']),
   ('Gold Sarcophagus banish Shif từ Deck.', ['Gold Sarcophagus','Shif, Fairy of the Ghoti']),
   ('Standby Phase kế tiếp, Shif tự gọi; trong Main Phase đối thủ dùng Shif Tuner Level 2 và Leaffish Level 4 để Synchro Arionpos.', ['Shif, Fairy of the Ghoti','Lifeless Leaffish','Arionpos, Serpent of the Ghoti'])],
  ['Arionpos, Serpent of the Ghoti'],'Arionpos trong lượt đối thủ nếu Leaffish còn trên sân; xử lý hiệu ứng banish Fish để nối các nhánh sau.',tags=['synchro','banish','control'])
p('Invoked Dogmatika',
  'Aleister cung cấp Fusion, Dogmatika đổi Extra Deck lấy tài nguyên; mẫu WCS kết hợp Regenesis làm nhánh quái lớn.',
  'Fusion Mechaba trước Nadir/Ecclesia để không vướng khóa Extra Deck; giữ đúng loại bài trên tay cho negate Mechaba.',
  'Super Polymerization mở đường trước Aleister, Nadir/N\'tss xử lý thêm bài sau khi đã Fusion.',
  'Invocation dùng Aleister trong GY và LIGHT trên sân/GY để gọi Mechaba; kiểm tra nguyên liệu trước resolve.',
  'Mechaba và Dogmatika cung cấp hai lớp tương tác.', 'Negate Aleister và thứ tự khóa sai làm thiếu Fusion.',
  ['Aleister the Invoker'],0,
  [('Normal Summon Aleister, tìm Invocation.', ['Aleister the Invoker','Invocation']),
   ('Link Aleister thành Almiraj rồi Link Almiraj thành Secure Gardna LIGHT.', ['Aleister the Invoker','Salamangreat Almiraj','Secure Gardna']),
   ('Invocation banish Aleister trong GY và Secure Gardna trên sân để Fusion Mechaba; Invocation trong GY xào lại Deck và lấy Aleister banish về tay.', ['Invocation','Aleister the Invoker','Secure Gardna','Invoked Mechaba'])],
  ['Invoked Mechaba'],'Mechaba và Aleister hồi tay; Aleister có thể làm cost negate hiệu ứng quái.',tags=['fusion','control','midrange'])
p('Mitsurugi Orcust',
  'Biến thể đang có kết quả giải trên MDM: Mitsurugi tạo nhánh Ritual, Orcust dùng GY để nối Link và tài nguyên.',
  'Làm Ritual trước các hiệu ứng Orcust khóa DARK nếu cần quái không DARK; giữ Babel cho tương tác GY.',
  'Dingirsu gửi bài không cần destroy, Mitsurugi xử lý sân qua Ritual và Tribute.',
  'Orcust Harp Horror khóa Special Summon vào DARK sau khi resolve; gọi Ritual không DARK trước đó.',
  'Hai engine cung cấp tương tác qua Ritual và GY.', 'Khóa GY hoặc negate search Ritual làm thiếu nhánh dự phòng.',
  ['Orcust Harp Horror'],1,
  [('Đưa Harp Horror vào GY bằng cost/hiệu ứng của bài khác; line yêu cầu một lá gửi quái phù hợp, không coi Harp trên tay là starter một lá.', ['Orcust Harp Horror']),
   ('Banish Harp từ GY để gọi Orcust Knightmare từ Deck.', ['Orcust Harp Horror','Orcust Knightmare']),
   ('Dùng Knightmare và một Effect Monster khác đã có trên sân để Link Galatea; cần body thứ hai trước bước này.', ['Orcust Knightmare','Galatea, the Orcust Automaton'])],
  [],'Nhánh Orcust chuẩn bị Galatea khi có lá gửi GY và body; Ritual phải được triển khai trước khóa DARK.',difficulty='advanced',tags=['ritual','link','graveyard'])
